// ─── DEVELOPER PACKS CONTENT LIBRARY ───

export const DEV_CONTENT: Record<string, string[]> = {

  code: [
    'function greet(name) { return `Hello, ${name}!`; }',
    'const arr = [1, 2, 3].map(x => x * 2).filter(x => x > 2);',
    'class User { constructor(name) { this.name = name; } }',
    'if (condition && flag) { execute(); } else { fallback(); }',
    'const sum = (a, b) => a + b; const result = sum(10, 20);',
    'try { await fetch(url); } catch (err) { console.error(err); }',
    'for (let i = 0; i < arr.length; i++) { process(arr[i]); }',
    'switch(action) { case "ADD": return add(); case "DEL": return del(); }',
    'const [state, setState] = useState(0); useEffect(() => {}, []);',
    'export default function handler(req, res) { res.json({ ok: true }); }',
    'const obj = { ...defaults, ...overrides, timestamp: Date.now() };',
    'Promise.all([fetchA(), fetchB()]).then(([a, b]) => merge(a, b));',
    'const debounce = (fn, ms) => { let t; return (...a) => { clearTimeout(t); t = setTimeout(() => fn(...a), ms); }; };',
    'document.querySelector("#app").addEventListener("click", handler);',
    'const result = items.reduce((acc, item) => acc + item.price, 0);',
    'Object.keys(config).forEach(key => validate(config[key]));',
    'const proxy = new Proxy(target, { get: (obj, prop) => obj[prop] });',
    'async function* generate(n) { for (let i = 0; i < n; i++) yield i; }',
    'const unique = [...new Set(array)]; const flat = nested.flat(Infinity);',
    'class EventEmitter { on(e, fn) { (this.events[e] ||= []).push(fn); } }',
    'const pipe = (...fns) => (x) => fns.reduce((v, f) => f(v), x);',
    'const memoize = (fn) => { const c = {}; return (k) => c[k] ||= fn(k); };',
    'window.requestAnimationFrame(() => { element.style.opacity = "1"; });',
    'fetch("/api/data", { method: "POST", body: JSON.stringify(payload) });',
    'const deepClone = (obj) => JSON.parse(JSON.stringify(obj));',
    'arr.sort((a, b) => a.name.localeCompare(b.name));',
    'function curry(fn) { return (a) => (b) => fn(a, b); }',
    'const observer = new IntersectionObserver(callback, { threshold: 0.5 });',
    'const worker = new Worker("worker.js"); worker.postMessage({ cmd: "start" });',
    'const [first, ...rest] = array; const { name, ...props } = object;',
    'navigator.clipboard.writeText(text).then(() => alert("Copied!"));',
    'const regex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/;',
    'localStorage.setItem("token", jwt); const t = localStorage.getItem("token");',
    'const ws = new WebSocket("wss://server.com"); ws.onmessage = handleMsg;',
    'const canvas = document.getElementById("c"); const ctx = canvas.getContext("2d");',
    'performance.mark("start"); doWork(); performance.measure("op", "start");',
    'const ab = new ArrayBuffer(16); const view = new DataView(ab);',
    'const stream = fs.createReadStream("file.txt", { encoding: "utf8" });',
    'const queue = []; queue.push(item); const next = queue.shift();',
    'class LinkedList { constructor() { this.head = null; this.size = 0; } }',
    'function binarySearch(arr, t) { let l = 0, r = arr.length - 1; /* ... */ }',
    'const tree = { val: 1, left: { val: 2 }, right: { val: 3 } };',
    'function dfs(node, visited = new Set()) { visited.add(node); /* ... */ }',
    'const matrix = Array.from({ length: n }, () => new Array(m).fill(0));',
    'class Stack { #items = []; push(v) { this.#items.push(v); } pop() { return this.#items.pop(); } }',
    'const throttle = (fn, ms) => { let l = 0; return (...a) => { if (Date.now() - l > ms) { l = Date.now(); fn(...a); } }; };',
    'const hash = new Map(); hash.set("key", val); hash.get("key"); hash.delete("key");',
    'function* fibonacci() { let a = 0, b = 1; while(true) { yield a; [a, b] = [b, a + b]; } }',
    'const { data, error } = await supabase.from("posts").select("*").eq("id", 1);',
    'export const middleware = (req, res, next) => { auth(req) ? next() : res.status(401).end(); };',
  ],

  javascript: [
    'const fetchUser = async (id) => { const res = await api.get(`/users/${id}`); return res.data; };',
    'const express = require("express"); const app = express(); app.listen(3000);',
    'const router = express.Router(); router.get("/", (req, res) => res.json({ ok: true }));',
    'document.addEventListener("DOMContentLoaded", () => { init(); });',
    'const promise = new Promise((resolve, reject) => { setTimeout(resolve, 1000); });',
    'Array.prototype.flatten = function() { return this.reduce((a, b) => a.concat(b), []); };',
    'const EventEmitter = require("events"); const emitter = new EventEmitter();',
    'module.exports = { add: (a, b) => a + b, sub: (a, b) => a - b };',
    'const { readFile, writeFile } = require("fs/promises");',
    'const server = http.createServer((req, res) => { res.end("Hello"); }); server.listen(8080);',
    'const cache = new Map(); function memoize(fn) { return (k) => cache.get(k) ?? cache.set(k, fn(k)).get(k); }',
    'const debounce = (fn, delay) => { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), delay); }; };',
    'const compose = (...fns) => (x) => fns.reduceRight((acc, fn) => fn(acc), x);',
    'class Observable { constructor(fn) { this._fn = fn; } subscribe(obs) { this._fn(obs); } }',
    'const proxy = new Proxy({}, { get(t, p) { return p in t ? t[p] : 42; } });',
    'WeakRef && new WeakRef(obj); const registry = new FinalizationRegistry(cb);',
    'const channel = new BroadcastChannel("app"); channel.postMessage("ping");',
    'const iter = { [Symbol.iterator]() { let i = 0; return { next: () => ({ value: i++, done: i > 5 }) }; } };',
    'Object.defineProperty(obj, "prop", { get() { return this._val; }, set(v) { this._val = v; } });',
    'const worker = new SharedWorker("shared.js"); worker.port.start();',
    'async function retry(fn, n) { for (let i = 0; i < n; i++) { try { return await fn(); } catch(e) { if (i === n-1) throw e; } } }',
    'const controller = new AbortController(); fetch(url, { signal: controller.signal });',
    'queueMicrotask(() => { console.log("microtask"); }); setTimeout(() => console.log("macro"), 0);',
    'structuredClone(deepObj); // deep clone without JSON limitations',
    'const entries = Object.entries(obj).filter(([k, v]) => v !== null);',
    'const { readable, writable } = new TransformStream(); const writer = writable.getWriter();',
    'class PubSub { #subs = {}; on(e, fn) { (this.#subs[e] ??= []).push(fn); } emit(e, d) { this.#subs[e]?.forEach(f => f(d)); } }',
    'const decoder = new TextDecoder("utf-8"); const text = decoder.decode(buffer);',
    'const blob = new Blob([json], { type: "application/json" }); const url = URL.createObjectURL(blob);',
    'navigator.serviceWorker.register("/sw.js").then(reg => console.log("SW Registered"));',
    'const db = indexedDB.open("myDB", 1); db.onupgradeneeded = (e) => { e.target.result.createObjectStore("items"); };',
    'const params = new URLSearchParams(window.location.search); const id = params.get("id");',
    'document.cookie = "theme=dark; path=/; max-age=86400; secure; samesite=strict";',
    'const observer = new MutationObserver((list) => { for (const mutation of list) { handle(mutation); } });',
    'const perf = performance.getEntriesByType("navigation")[0]; console.log(perf.domContentLoadedEventEnd);',
    'const ac = new AudioContext(); const osc = ac.createOscillator(); osc.connect(ac.destination);',
    'const { port1, port2 } = new MessageChannel(); port1.onmessage = (e) => handle(e.data);',
    'Reflect.defineProperty(target, "key", { value: 42, writable: false });',
    'const weakMap = new WeakMap(); weakMap.set(obj, "metadata"); weakMap.get(obj);',
    'globalThis.addEventListener("unhandledrejection", (e) => log(e.reason));',
    'const sym = Symbol("unique"); const obj = { [sym]: "hidden" }; obj[sym];',
    'using(resource) { /* auto-dispose at end of scope */ } // TC39 Stage 3',
    'const pipeline = input |> transform1 |> transform2 |> output; // pipeline operator',
    'const rec = JSON.parse(JSON.stringify(original), (key, val) => key === "date" ? new Date(val) : val);',
    'const scheduler = new Scheduler(); scheduler.postTask(() => heavyWork(), { priority: "background" });',
    'const stream = new ReadableStream({ start(ctrl) { ctrl.enqueue("data"); ctrl.close(); } });',
    'Error.captureStackTrace(this, CustomError); this.code = "CUSTOM_ERR";',
    'const gen = function* () { yield 1; yield* [2, 3]; yield 4; }; const it = gen();',
    'Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(1234);',
    'PerformanceObserver((list) => { for (const entry of list.getEntries()) log(entry); });',
  ],

  typescript: [
    'interface User { id: number; name: string; email: string; role: "admin" | "user"; }',
    'type Result<T> = { success: true; data: T } | { success: false; error: string };',
    'const getUser = (id: number): Promise<User> => fetchAPI(`/users/${id}`);',
    'function identity<T>(arg: T): T { return arg; }',
    'type DeepPartial<T> = { [P in keyof T]?: DeepPartial<T[P]> };',
    'enum Status { Active = "ACTIVE", Inactive = "INACTIVE", Pending = "PENDING" }',
    'const config: Readonly<Config> = Object.freeze({ port: 3000, host: "localhost" });',
    'type EventMap = { click: MouseEvent; keydown: KeyboardEvent; scroll: Event };',
    'class Repository<T extends Entity> { async findById(id: string): Promise<T | null> { /* ... */ } }',
    'const assertNever = (x: never): never => { throw new Error(`Unexpected: ${x}`); };',
    'type Awaited<T> = T extends Promise<infer U> ? Awaited<U> : T;',
    'interface Props { children: React.ReactNode; className?: string; onClick?: () => void; }',
    'const useTypedSelector = <T>(selector: (state: RootState) => T): T => useSelector(selector);',
    'type ExtractRouteParams<T extends string> = T extends `${string}:${infer P}/${infer R}` ? { [K in P]: string } & ExtractRouteParams<R> : {};',
    'declare module "*.svg" { const content: React.FC<React.SVGProps<SVGSVGElement>>; export default content; }',
    'const tuple = <T extends unknown[]>(...args: T): T => args;',
    'type Prettify<T> = { [K in keyof T]: T[K] } & {};',
    'abstract class Base { abstract render(): JSX.Element; protected log(msg: string) { console.log(msg); } }',
    'const is = <T>(value: unknown, guard: (v: unknown) => v is T): value is T => guard(value);',
    'type Flatten<T> = T extends Array<infer U> ? Flatten<U> : T;',
    'interface ApiResponse<T = unknown> { status: number; data: T; message: string; timestamp: Date; }',
    'const createStore = <T>(initial: T) => { let state = initial; return { get: () => state, set: (v: T) => { state = v; } }; };',
    'type Brand<T, B extends string> = T & { __brand: B };',
    'type UserId = Brand<string, "UserId">; type PostId = Brand<string, "PostId">;',
    'function exhaustiveCheck(param: never): never { throw new Error(`Unhandled case: ${param}`); }',
    'type MaybePromise<T> = T | Promise<T>; type MaybeArray<T> = T | T[];',
    'const z = zod.object({ name: zod.string().min(1), age: zod.number().int().positive() });',
    'type Middleware<T> = (ctx: T, next: () => Promise<void>) => Promise<void>;',
    'as const satisfies Record<string, { label: string; value: number }>;',
    'type PathOf<T, K extends keyof T = keyof T> = K extends string ? T[K] extends object ? `${K}.${PathOf<T[K]>}` : K : never;',
    'const handler: NextApiHandler<ResponseData> = async (req, res) => { res.status(200).json({ name: "OK" }); };',
    'type RecursiveRequired<T> = { [P in keyof T]-?: RecursiveRequired<T[P]> };',
    'interface EventEmitter<Events extends Record<string, unknown>> { on<K extends keyof Events>(event: K, listener: (data: Events[K]) => void): void; }',
    'const parseJSON = <T>(json: string): T => JSON.parse(json) as T;',
    'type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void ? I : never;',
    'class TypedEventTarget<T extends Record<string, Event>> extends EventTarget { dispatch<K extends keyof T>(type: K, event: T[K]) { this.dispatchEvent(event); } }',
    'const builder = <T>() => ({ add: <K extends string, V>(k: K, v: V) => builder<T & Record<K, V>>(), build: () => ({} as T) });',
    'type IsEqual<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;',
    'type TupleToUnion<T extends readonly unknown[]> = T[number];',
    'interface Disposable { [Symbol.dispose](): void; }',
    'const withRetry = <T>(fn: () => Promise<T>, retries = 3): Promise<T> => fn().catch(e => retries > 0 ? withRetry(fn, retries - 1) : Promise.reject(e));',
    'type Last<T extends readonly unknown[]> = T extends [...infer _, infer L] ? L : never;',
    'const safeAccess = <T, K extends keyof T>(obj: T, key: K): T[K] | undefined => obj?.[key];',
    'type StringKeys<T> = Extract<keyof T, string>;',
    'type PickByType<T, V> = { [K in keyof T as T[K] extends V ? K : never]: T[K] };',
    'const zodSchema = z.discriminatedUnion("type", [z.object({ type: z.literal("a"), val: z.string() }), z.object({ type: z.literal("b"), num: z.number() })]);',
    'type InferZodType<T extends z.ZodTypeAny> = z.infer<T>;',
    'declare global { interface Window { __APP_STATE__: AppState; } }',
    'type OmitByType<T, V> = { [K in keyof T as T[K] extends V ? never : K]: T[K] };',
    'const typed = <const T extends readonly string[]>(arr: T): T => arr;',
  ],

  react: [
    'import React, { useState } from "react"; export const Counter = () => { const [count, setCount] = useState(0); return <button onClick={() => setCount(count + 1)}>{count}</button>; };',
    'const App = () => { const [theme, setTheme] = useState("dark"); return <ThemeContext.Provider value={theme}><Main /></ThemeContext.Provider>; };',
    'useEffect(() => { const handler = (e) => setPos({ x: e.clientX, y: e.clientY }); window.addEventListener("mousemove", handler); return () => window.removeEventListener("mousemove", handler); }, []);',
    'const Input = React.forwardRef<HTMLInputElement, Props>((props, ref) => <input ref={ref} {...props} />);',
    'const useFetch = <T>(url: string) => { const [data, setData] = useState<T | null>(null); useEffect(() => { fetch(url).then(r => r.json()).then(setData); }, [url]); return data; };',
    'const memo = React.memo(({ items }: { items: Item[] }) => <ul>{items.map(i => <li key={i.id}>{i.name}</li>)}</ul>);',
    'const LazyComponent = React.lazy(() => import("./HeavyComponent")); <Suspense fallback={<Loading />}><LazyComponent /></Suspense>;',
    'const reducer = (state, action) => { switch (action.type) { case "INC": return { count: state.count + 1 }; default: return state; } };',
    'const [state, dispatch] = useReducer(reducer, { count: 0 }); <button onClick={() => dispatch({ type: "INC" })}>+</button>;',
    'const PrivateRoute = ({ children }) => { const { user } = useAuth(); return user ? children : <Navigate to="/login" />; };',
    'const ctx = createContext<{ user: User | null; login: (u: User) => void }>({ user: null, login: () => {} });',
    'function ErrorBoundary({ children }) { const [error, setError] = useState(null); if (error) return <FallbackUI />; return children; }',
    'const Portal = ({ children }) => createPortal(children, document.getElementById("modal-root")!);',
    'const useDebounce = <T>(value: T, delay: number): T => { const [dv, setDv] = useState(value); useEffect(() => { const t = setTimeout(() => setDv(value), delay); return () => clearTimeout(t); }, [value, delay]); return dv; };',
    'const useLocalStorage = <T>(key: string, init: T) => { const [val, setVal] = useState<T>(() => { const s = localStorage.getItem(key); return s ? JSON.parse(s) : init; }); useEffect(() => localStorage.setItem(key, JSON.stringify(val)), [key, val]); return [val, setVal] as const; };',
    'const InfiniteScroll = () => { const ref = useRef<HTMLDivElement>(null); useEffect(() => { const observer = new IntersectionObserver(([e]) => { if (e.isIntersecting) loadMore(); }); if (ref.current) observer.observe(ref.current); return () => observer.disconnect(); }, []); return <div ref={ref} />; };',
    '<form onSubmit={handleSubmit(onSubmit)}><input {...register("email", { required: true })} /><button type="submit">Send</button></form>',
    'const Toast = ({ message, type }) => <motion.div initial={{ opacity: 0, y: 50 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className={`toast toast-${type}`}>{message}</motion.div>;',
    'const { data, isLoading, error } = useQuery({ queryKey: ["users"], queryFn: fetchUsers, staleTime: 5 * 60 * 1000 });',
    'const mutation = useMutation({ mutationFn: createUser, onSuccess: () => queryClient.invalidateQueries(["users"]) });',
    'const Tabs = ({ tabs }) => { const [active, setActive] = useState(0); return <div>{tabs.map((t, i) => <button key={i} onClick={() => setActive(i)} className={i === active ? "active" : ""}>{t.label}</button>)}<div>{tabs[active].content}</div></div>; };',
    'const VirtualList = ({ items, height, rowHeight }) => { const [offset, setOffset] = useState(0); const visible = Math.ceil(height / rowHeight); const start = Math.floor(offset / rowHeight); return <div style={{ height }} onScroll={e => setOffset(e.target.scrollTop)}><div style={{ height: items.length * rowHeight }}>{items.slice(start, start + visible).map(renderRow)}</div></div>; };',
    'export const getServerSideProps = async (ctx) => { const session = await getSession(ctx); if (!session) return { redirect: { destination: "/login" } }; return { props: { user: session.user } }; };',
    'const useWindowSize = () => { const [size, setSize] = useState({ w: 0, h: 0 }); useEffect(() => { const h = () => setSize({ w: window.innerWidth, h: window.innerHeight }); window.addEventListener("resize", h); h(); return () => window.removeEventListener("resize", h); }, []); return size; };',
    'const Skeleton = ({ width, height }) => <div className="animate-pulse bg-gray-200 rounded" style={{ width, height }} />;',
    'const useClickOutside = (ref, handler) => { useEffect(() => { const listener = (e) => { if (!ref.current?.contains(e.target)) handler(); }; document.addEventListener("mousedown", listener); return () => document.removeEventListener("mousedown", listener); }, [ref, handler]); };',
    'const DarkModeToggle = () => { const [dark, setDark] = useState(false); useEffect(() => { document.body.classList.toggle("dark", dark); }, [dark]); return <button onClick={() => setDark(!dark)}>{dark ? "Light" : "Dark"}</button>; };',
    '<AnimatePresence>{show && <motion.div key="modal" initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.9 }} transition={{ type: "spring" }}><Modal /></motion.div>}</AnimatePresence>',
    'const DataTable = ({ columns, data }) => <table><thead><tr>{columns.map(c => <th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{data.map(row => <tr key={row.id}>{columns.map(c => <td key={c.key}>{row[c.key]}</td>)}</tr>)}</tbody></table>;',
    'const useMediaQuery = (query) => { const [matches, set] = useState(false); useEffect(() => { const mq = window.matchMedia(query); set(mq.matches); const h = (e) => set(e.matches); mq.addEventListener("change", h); return () => mq.removeEventListener("change", h); }, [query]); return matches; };',
    'const Tooltip = ({ children, text }) => { const [show, setShow] = useState(false); return <div onMouseEnter={() => setShow(true)} onMouseLeave={() => setShow(false)}>{children}{show && <span className="tooltip">{text}</span>}</div>; };',
    'const Accordion = ({ items }) => { const [open, setOpen] = useState(-1); return <div>{items.map((item, i) => <div key={i}><button onClick={() => setOpen(open === i ? -1 : i)}>{item.title}</button>{open === i && <div>{item.content}</div>}</div>)}</div>; };',
    'const Breadcrumbs = ({ items }) => <nav>{items.map((item, i) => <span key={i}>{i > 0 && " / "}<Link href={item.href}>{item.label}</Link></span>)}</nav>;',
    'const SearchBar = () => { const [query, setQuery] = useState(""); const debouncedQuery = useDebounce(query, 300); useEffect(() => { if (debouncedQuery) search(debouncedQuery); }, [debouncedQuery]); return <input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search..." />; };',
    'const Pagination = ({ page, total, onChange }) => <div>{Array.from({ length: total }, (_, i) => <button key={i} onClick={() => onChange(i + 1)} className={page === i + 1 ? "active" : ""}>{i + 1}</button>)}</div>;',
    'const FileUpload = () => { const [file, setFile] = useState(null); const handleDrop = (e) => { e.preventDefault(); setFile(e.dataTransfer.files[0]); }; return <div onDrop={handleDrop} onDragOver={e => e.preventDefault()}>{file ? file.name : "Drop file here"}</div>; };',
    'const useInterval = (callback, delay) => { const saved = useRef(callback); useEffect(() => { saved.current = callback; }, [callback]); useEffect(() => { if (delay !== null) { const id = setInterval(() => saved.current(), delay); return () => clearInterval(id); } }, [delay]); };',
    'const CopyButton = ({ text }) => { const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000); }; return <button onClick={copy}>{copied ? "Copied!" : "Copy"}</button>; };',
    'const Modal = ({ isOpen, onClose, children }) => { if (!isOpen) return null; return createPortal(<div className="overlay" onClick={onClose}><div className="modal" onClick={e => e.stopPropagation()}>{children}</div></div>, document.body); };',
    'const ProgressBar = ({ value, max }) => <div className="progress-bar"><div className="progress-fill" style={{ width: `${(value / max) * 100}%` }} /><span>{Math.round((value / max) * 100)}%</span></div>;',
    'const Select = ({ options, value, onChange }) => <select value={value} onChange={e => onChange(e.target.value)}>{options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select>;',
    'const Badge = ({ count, children }) => <div className="badge-wrapper">{children}{count > 0 && <span className="badge">{count > 99 ? "99+" : count}</span>}</div>;',
    'const Stepper = ({ steps, current }) => <div className="stepper">{steps.map((s, i) => <div key={i} className={`step ${i <= current ? "active" : ""}`}><span className="step-number">{i + 1}</span><span>{s}</span></div>)}</div>;',
    'const ColorPicker = () => { const [color, setColor] = useState("#39FF14"); return <div><input type="color" value={color} onChange={e => setColor(e.target.value)} /><span style={{ color }}>{color}</span></div>; };',
    'const CountdownTimer = ({ seconds }) => { const [time, setTime] = useState(seconds); useEffect(() => { if (time <= 0) return; const t = setTimeout(() => setTime(time - 1), 1000); return () => clearTimeout(t); }, [time]); return <span>{Math.floor(time / 60)}:{String(time % 60).padStart(2, "0")}</span>; };',
    'function useOnScreen(ref) { const [visible, set] = useState(false); useEffect(() => { const obs = new IntersectionObserver(([e]) => set(e.isIntersecting)); if (ref.current) obs.observe(ref.current); return () => obs.disconnect(); }, [ref]); return visible; }',
    'const StarRating = ({ rating, onRate }) => <div>{[1, 2, 3, 4, 5].map(n => <span key={n} onClick={() => onRate(n)} style={{ cursor: "pointer", color: n <= rating ? "#FCD34D" : "#555" }}>★</span>)}</div>;',
    'const ToggleSwitch = ({ on, onToggle }) => <button onClick={onToggle} className={`toggle ${on ? "on" : "off"}`}><span className="toggle-knob" /></button>;',
    'const Tag = ({ label, onRemove }) => <span className="tag">{label}<button onClick={onRemove}>×</button></span>;',
  ],

  python: [
    'def calculate_sum(a, b):\n    return a + b\n\nif __name__ == "__main__":\n    print("Hello")',
    'class LinkedList:\n    def __init__(self):\n        self.head = None\n    def append(self, data):\n        node = Node(data)',
    'import os\nimport sys\n\ndef main():\n    path = os.path.join(os.getcwd(), "data")\n    print(f"Working in {path}")',
    'from typing import List, Dict, Optional\ndef parse_config(path: str) -> Dict[str, str]:\n    with open(path) as f:\n        return json.load(f)',
    'def fibonacci(n: int) -> list:\n    a, b = 0, 1\n    result = []\n    for _ in range(n):\n        result.append(a)\n        a, b = b, a + b\n    return result',
    'class DataProcessor:\n    def __init__(self, data):\n        self.data = data\n    def clean(self):\n        return [x.strip() for x in self.data if x]',
    '@app.route("/api/users", methods=["GET"])\ndef get_users():\n    users = User.query.all()\n    return jsonify([u.to_dict() for u in users])',
    'def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid',
    'async def fetch_data(url: str) -> dict:\n    async with aiohttp.ClientSession() as session:\n        async with session.get(url) as response:\n            return await response.json()',
    'with open("output.csv", "w", newline="") as f:\n    writer = csv.writer(f)\n    writer.writerow(["Name", "Age", "City"])\n    writer.writerows(data)',
    'try:\n    result = process(data)\nexcept ValueError as e:\n    logger.error(f"Invalid value: {e}")\nexcept Exception as e:\n    logger.critical(f"Unexpected error: {e}")\nfinally:\n    cleanup()',
    'from dataclasses import dataclass\n\n@dataclass\nclass User:\n    name: str\n    age: int\n    email: str = ""',
    'def decorator(func):\n    @functools.wraps(func)\n    def wrapper(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        print(f"Took {time.time() - start:.2f}s")\n        return result\n    return wrapper',
    'import unittest\n\nclass TestMath(unittest.TestCase):\n    def test_add(self):\n        self.assertEqual(add(2, 3), 5)\n    def test_subtract(self):\n        self.assertEqual(sub(5, 3), 2)',
    'from collections import Counter, defaultdict\nword_count = Counter(words)\nmost_common = word_count.most_common(10)',
    'import numpy as np\narr = np.array([[1, 2, 3], [4, 5, 6]])\nmean = np.mean(arr, axis=0)\nresult = np.dot(arr.T, arr)',
    'import pandas as pd\ndf = pd.read_csv("data.csv")\ndf = df.dropna()\ndf["total"] = df["price"] * df["quantity"]',
    'def quicksort(arr):\n    if len(arr) <= 1:\n        return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    mid = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quicksort(left) + mid + quicksort(right)',
    'class Singleton:\n    _instance = None\n    def __new__(cls):\n        if cls._instance is None:\n            cls._instance = super().__new__(cls)\n        return cls._instance',
    'from abc import ABC, abstractmethod\nclass Shape(ABC):\n    @abstractmethod\n    def area(self) -> float:\n        pass\n    @abstractmethod\n    def perimeter(self) -> float:\n        pass',
    'import re\npattern = r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"\nis_valid = bool(re.match(pattern, email))',
    'def flatten(lst):\n    for item in lst:\n        if isinstance(item, list):\n            yield from flatten(item)\n        else:\n            yield item',
    'from contextlib import contextmanager\n\n@contextmanager\ndef timer(label):\n    start = time.time()\n    yield\n    print(f"{label}: {time.time() - start:.3f}s")',
    'from itertools import chain, combinations\ndef powerset(iterable):\n    s = list(iterable)\n    return chain.from_iterable(combinations(s, r) for r in range(len(s) + 1))',
    'from pathlib import Path\nfor file in Path(".").rglob("*.py"):\n    content = file.read_text()\n    if "TODO" in content:\n        print(f"{file}: contains TODO")',
    'class BinaryTree:\n    def __init__(self, val):\n        self.val = val\n        self.left = None\n        self.right = None\n    def inorder(self):\n        if self.left: yield from self.left.inorder()\n        yield self.val\n        if self.right: yield from self.right.inorder()',
    'from functools import lru_cache\n\n@lru_cache(maxsize=128)\ndef expensive_computation(n):\n    if n < 2:\n        return n\n    return expensive_computation(n - 1) + expensive_computation(n - 2)',
    'import asyncio\n\nasync def main():\n    tasks = [fetch(url) for url in urls]\n    results = await asyncio.gather(*tasks)\n    return results',
    'class Stack:\n    def __init__(self):\n        self._items = []\n    def push(self, item):\n        self._items.append(item)\n    def pop(self):\n        return self._items.pop()\n    def peek(self):\n        return self._items[-1]',
    'import sqlite3\nconn = sqlite3.connect("database.db")\ncursor = conn.cursor()\ncursor.execute("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT)")\nconn.commit()',
    'import argparse\nparser = argparse.ArgumentParser(description="CLI Tool")\nparser.add_argument("--verbose", "-v", action="store_true")\nparser.add_argument("input", type=str, help="Input file")\nargs = parser.parse_args()',
    'from typing import TypeVar, Generic\nT = TypeVar("T")\nclass Queue(Generic[T]):\n    def __init__(self):\n        self._items: list[T] = []\n    def enqueue(self, item: T) -> None:\n        self._items.append(item)',
    'import hashlib\ndef hash_password(password: str, salt: str) -> str:\n    return hashlib.pbkdf2_hmac("sha256", password.encode(), salt.encode(), 100000).hex()',
    'from enum import Enum, auto\nclass Color(Enum):\n    RED = auto()\n    GREEN = auto()\n    BLUE = auto()',
    'import logging\nlogging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")\nlogger = logging.getLogger(__name__)',
    'class Meta(type):\n    def __new__(mcs, name, bases, namespace):\n        cls = super().__new__(mcs, name, bases, namespace)\n        cls.registry = {}\n        return cls',
    'def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)',
    'import json\nwith open("config.json") as f:\n    config = json.load(f)\nprint(f"Server: {config[\"host\"]}:{config[\"port\"]}")',
    'from concurrent.futures import ThreadPoolExecutor\nwith ThreadPoolExecutor(max_workers=4) as pool:\n    results = list(pool.map(process_item, items))',
    'class Property:\n    def __init__(self):\n        self._value = None\n    def __get__(self, obj, objtype=None):\n        return self._value\n    def __set__(self, obj, value):\n        self._value = value',
    'import socket\nwith socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:\n    s.bind(("localhost", 8080))\n    s.listen()\n    conn, addr = s.accept()',
    'from pydantic import BaseModel, validator\nclass UserCreate(BaseModel):\n    name: str\n    email: str\n    @validator("email")\n    def validate_email(cls, v):\n        if "@" not in v:\n            raise ValueError("Invalid email")\n        return v',
    'import threading\nlock = threading.Lock()\ndef thread_safe_increment():\n    with lock:\n        global counter\n        counter += 1',
    'from typing import Protocol\nclass Comparable(Protocol):\n    def __lt__(self, other) -> bool: ...\n    def __eq__(self, other) -> bool: ...',
    'import pickle\nwith open("model.pkl", "wb") as f:\n    pickle.dump(trained_model, f)\nwith open("model.pkl", "rb") as f:\n    model = pickle.load(f)',
    'class Matrix:\n    def __init__(self, data):\n        self.data = data\n    def __mul__(self, other):\n        return Matrix([[sum(a * b for a, b in zip(row, col)) for col in zip(*other.data)] for row in self.data])',
    'from flask import Flask, request, jsonify\napp = Flask(__name__)\n@app.route("/health")\ndef health():\n    return jsonify({"status": "ok"})',
    'import requests\nresponse = requests.get("https://api.example.com/data", headers={"Authorization": f"Bearer {token}"})\ndata = response.json()',
    'def lru_cache_manual(maxsize=128):\n    cache = OrderedDict()\n    def decorator(func):\n        def wrapper(*args):\n            if args in cache:\n                cache.move_to_end(args)\n                return cache[args]\n            result = func(*args)\n            cache[args] = result\n            if len(cache) > maxsize:\n                cache.popitem(last=False)\n            return result\n        return wrapper\n    return decorator',
  ],

  'html-css': [
    '<div class="container"><h1>Title</h1></div>\n\n.container { display: flex; }',
    '<header class="nav"><a href="/" class="logo">Brand</a><nav><a href="/about">About</a></nav></header>',
    '<form method="POST" action="/submit"><input type="text" name="email" required /><button type="submit">Send</button></form>',
    '.card { border-radius: 12px; padding: 24px; background: linear-gradient(135deg, #1a1a2e, #16213e); box-shadow: 0 4px 20px rgba(0,0,0,0.3); }',
    '@media (max-width: 768px) { .grid { grid-template-columns: 1fr; } .sidebar { display: none; } }',
    '<section class="hero"><h1>Welcome</h1><p>Build something amazing today.</p><a href="/start" class="btn btn-primary">Get Started</a></section>',
    '.btn { display: inline-flex; align-items: center; padding: 10px 24px; border-radius: 8px; font-weight: 600; transition: all 0.2s ease; }',
    '<table class="data-table"><thead><tr><th>Name</th><th>Age</th><th>Role</th></tr></thead><tbody><tr><td>Alice</td><td>30</td><td>Admin</td></tr></tbody></table>',
    ':root { --primary: #39FF14; --bg: #0a0a0a; --text: #e5e5e5; --border: rgba(255,255,255,0.08); }',
    '.glassmorphism { background: rgba(255, 255, 255, 0.05); backdrop-filter: blur(20px); border: 1px solid rgba(255, 255, 255, 0.1); }',
    '<div class="grid"><div class="col-span-2">Main</div><div>Sidebar</div></div>\n\n.grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }',
    '@keyframes fadeIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }\n.animate { animation: fadeIn 0.5s ease forwards; }',
    '.tooltip { position: relative; } .tooltip::after { content: attr(data-tip); position: absolute; bottom: 100%; left: 50%; transform: translateX(-50%); padding: 4px 8px; background: #333; color: #fff; border-radius: 4px; font-size: 12px; white-space: nowrap; opacity: 0; transition: opacity 0.2s; } .tooltip:hover::after { opacity: 1; }',
    '<details><summary>FAQ: How to get started?</summary><p>Follow the documentation guide for step-by-step instructions.</p></details>',
    '<dialog id="modal"><h2>Confirm Action</h2><p>Are you sure?</p><button onclick="this.closest(\'dialog\').close()">Cancel</button></dialog>',
    '.dark-mode { background-color: #0f0f0f; color: #e0e0e0; } .dark-mode .card { background-color: #1a1a1a; border-color: #2a2a2a; }',
    '.spinner { width: 40px; height: 40px; border: 4px solid rgba(255,255,255,0.1); border-top-color: #39FF14; border-radius: 50%; animation: spin 0.8s linear infinite; } @keyframes spin { to { transform: rotate(360deg); } }',
    '<picture><source srcset="hero.webp" type="image/webp" /><source srcset="hero.jpg" type="image/jpeg" /><img src="hero.jpg" alt="Hero image" loading="lazy" /></picture>',
    '.container { max-width: 1200px; margin: 0 auto; padding: 0 16px; } @media (min-width: 1400px) { .container { max-width: 1400px; } }',
    '<ul class="breadcrumb"><li><a href="/">Home</a></li><li><a href="/products">Products</a></li><li aria-current="page">Details</li></ul>',
    '.flex-center { display: flex; justify-content: center; align-items: center; } .flex-between { display: flex; justify-content: space-between; align-items: center; }',
    '<meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="description" content="A modern web application" />',
    '.scroll-snap { scroll-snap-type: x mandatory; overflow-x: auto; } .scroll-snap > * { scroll-snap-align: start; flex-shrink: 0; width: 100%; }',
    '<progress value="75" max="100">75%</progress>\n\nprogress { appearance: none; height: 8px; border-radius: 4px; } progress::-webkit-progress-bar { background: #1a1a1a; border-radius: 4px; } progress::-webkit-progress-value { background: #39FF14; border-radius: 4px; }',
    '.truncate { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; } .line-clamp-3 { display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; }',
    '<input type="search" placeholder="Search..." />\n\ninput[type="search"] { padding: 8px 16px; border: 1px solid #333; border-radius: 24px; background: #111; color: #fff; outline: none; } input[type="search"]:focus { border-color: #39FF14; box-shadow: 0 0 0 3px rgba(57, 255, 20, 0.2); }',
    '.masonry { columns: 3; column-gap: 16px; } .masonry > * { break-inside: avoid; margin-bottom: 16px; }',
    '<nav aria-label="Pagination"><ul><li><a href="?page=1">1</a></li><li><a href="?page=2" aria-current="page">2</a></li><li><a href="?page=3">3</a></li></ul></nav>',
    '.gradient-text { background: linear-gradient(90deg, #39FF14, #00D4AA); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }',
    '<label class="switch"><input type="checkbox" /><span class="slider"></span></label>\n\n.switch { position: relative; width: 48px; height: 24px; } .slider { position: absolute; inset: 0; background: #333; border-radius: 24px; transition: 0.3s; cursor: pointer; } input:checked + .slider { background: #39FF14; }',
    '.sticky-header { position: sticky; top: 0; z-index: 100; backdrop-filter: blur(12px); background: rgba(10, 10, 10, 0.8); border-bottom: 1px solid rgba(255,255,255,0.05); }',
    '<fieldset><legend>Personal Information</legend><label>Name: <input type="text" name="name" /></label><label>Email: <input type="email" name="email" /></label></fieldset>',
    '.aspect-video { aspect-ratio: 16 / 9; } .aspect-square { aspect-ratio: 1 / 1; } .object-cover { object-fit: cover; width: 100%; height: 100%; }',
    '<div class="skeleton"><div class="skeleton-line"></div><div class="skeleton-line short"></div></div>\n\n.skeleton-line { height: 16px; background: linear-gradient(90deg, #1a1a1a 25%, #2a2a2a 50%, #1a1a1a 75%); background-size: 200% 100%; animation: shimmer 1.5s infinite; border-radius: 4px; margin-bottom: 8px; }',
    '.sr-only { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); border: 0; }',
    '<link rel="preconnect" href="https://fonts.googleapis.com" /><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />',
    '.container-query { container-type: inline-size; } @container (min-width: 400px) { .card { flex-direction: row; } }',
    '<div role="alert" class="toast"><svg class="icon" aria-hidden="true"></svg><p>Operation successful!</p><button aria-label="Dismiss">×</button></div>',
    '.hover-lift { transition: transform 0.2s ease, box-shadow 0.2s ease; } .hover-lift:hover { transform: translateY(-4px); box-shadow: 0 12px 24px rgba(0,0,0,0.3); }',
    '<img srcset="image-300.jpg 300w, image-600.jpg 600w, image-1200.jpg 1200w" sizes="(max-width: 600px) 300px, (max-width: 1200px) 600px, 1200px" src="image-600.jpg" alt="Responsive" />',
    '.custom-scrollbar::-webkit-scrollbar { width: 6px; } .custom-scrollbar::-webkit-scrollbar-track { background: #111; } .custom-scrollbar::-webkit-scrollbar-thumb { background: #333; border-radius: 3px; }',
    '<select name="country"><optgroup label="Europe"><option value="uk">United Kingdom</option><option value="de">Germany</option></optgroup><optgroup label="Asia"><option value="jp">Japan</option></optgroup></select>',
    '.neon-glow { text-shadow: 0 0 7px #39FF14, 0 0 10px #39FF14, 0 0 21px #39FF14, 0 0 42px #39FF14; }',
    '<footer class="footer"><div class="footer-grid"><div class="footer-col"><h4>Product</h4><a href="/features">Features</a></div><div class="footer-col"><h4>Company</h4><a href="/about">About</a></div></div><p>&copy; 2026 Brand. All rights reserved.</p></footer>',
    '.subgrid { display: grid; grid-template-columns: subgrid; grid-column: span 3; }',
    '<template id="card-template"><div class="card"><h3></h3><p></p></div></template>',
    '<div class="accordion" role="region"><h3><button aria-expanded="false" aria-controls="panel1">Section 1</button></h3><div id="panel1" role="region" hidden><p>Content here.</p></div></div>',
    '.print-only { display: none; } @media print { .print-only { display: block; } .no-print { display: none; } @page { margin: 2cm; } }',
    '<div class="tabs" role="tablist"><button role="tab" aria-selected="true" aria-controls="tab1">Tab 1</button><button role="tab" aria-selected="false" aria-controls="tab2">Tab 2</button></div><div role="tabpanel" id="tab1">Content 1</div>',
  ],

  sql: [
    'SELECT id, first_name, last_name, email FROM users WHERE status = "active" ORDER BY created_at DESC LIMIT 50;',
    'INSERT INTO orders (user_id, product_id, quantity, total) VALUES (1, 42, 3, 149.97);',
    'UPDATE products SET price = price * 0.9, updated_at = NOW() WHERE category = "electronics" AND stock > 0;',
    'DELETE FROM sessions WHERE last_activity < DATE_SUB(NOW(), INTERVAL 30 DAY);',
    'SELECT u.name, COUNT(o.id) AS order_count, SUM(o.total) AS total_spent FROM users u LEFT JOIN orders o ON u.id = o.user_id GROUP BY u.id HAVING total_spent > 1000 ORDER BY total_spent DESC;',
    'CREATE TABLE products (id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, price DECIMAL(10, 2) DEFAULT 0.00, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);',
    'ALTER TABLE users ADD COLUMN phone VARCHAR(20), ADD COLUMN verified BOOLEAN DEFAULT FALSE;',
    'CREATE INDEX idx_users_email ON users(email); CREATE INDEX idx_orders_user_date ON orders(user_id, created_at DESC);',
    'SELECT p.name, c.name AS category, p.price FROM products p INNER JOIN categories c ON p.category_id = c.id WHERE p.price BETWEEN 10 AND 100;',
    'WITH monthly_sales AS (SELECT DATE_TRUNC("month", created_at) AS month, SUM(total) AS revenue FROM orders GROUP BY month) SELECT month, revenue, LAG(revenue) OVER (ORDER BY month) AS prev_month FROM monthly_sales;',
    'SELECT DISTINCT ON (user_id) user_id, amount, created_at FROM payments ORDER BY user_id, created_at DESC;',
    'SELECT name, department, salary, RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dept_rank FROM employees;',
    'SELECT CASE WHEN age < 18 THEN "minor" WHEN age BETWEEN 18 AND 65 THEN "adult" ELSE "senior" END AS age_group, COUNT(*) FROM users GROUP BY age_group;',
    'CREATE VIEW active_users AS SELECT id, name, email, last_login FROM users WHERE status = "active" AND last_login > DATE_SUB(NOW(), INTERVAL 90 DAY);',
    'SELECT product_id, SUM(quantity) AS total_qty, AVG(unit_price) AS avg_price FROM order_items GROUP BY product_id HAVING total_qty > 100;',
    'BEGIN TRANSACTION; UPDATE accounts SET balance = balance - 500 WHERE id = 1; UPDATE accounts SET balance = balance + 500 WHERE id = 2; COMMIT;',
    'SELECT u.name, COALESCE(SUM(o.total), 0) AS lifetime_value FROM users u LEFT JOIN orders o ON u.id = o.user_id GROUP BY u.id ORDER BY lifetime_value DESC LIMIT 10;',
    'WITH RECURSIVE categories AS (SELECT id, name, parent_id, 0 AS depth FROM categories WHERE parent_id IS NULL UNION ALL SELECT c.id, c.name, c.parent_id, p.depth + 1 FROM categories c JOIN categories p ON c.parent_id = p.id) SELECT * FROM categories;',
    'CREATE TRIGGER update_timestamp BEFORE UPDATE ON products FOR EACH ROW SET NEW.updated_at = CURRENT_TIMESTAMP;',
    'SELECT EXTRACT(YEAR FROM created_at) AS year, EXTRACT(MONTH FROM created_at) AS month, COUNT(*) AS signups FROM users GROUP BY year, month ORDER BY year, month;',
    'SELECT id, name, email FROM users WHERE email LIKE "%@gmail.com" AND created_at >= "2025-01-01" ORDER BY name ASC;',
    'EXPLAIN ANALYZE SELECT * FROM orders WHERE user_id = 42 AND status = "completed" ORDER BY created_at DESC LIMIT 10;',
    'INSERT INTO audit_log (action, table_name, record_id, old_values, new_values, performed_by) VALUES ("UPDATE", "users", 42, \'{"name": "old"}\', \'{"name": "new"}\', 1);',
    'SELECT p.name, COUNT(r.id) AS review_count, ROUND(AVG(r.rating), 1) AS avg_rating FROM products p LEFT JOIN reviews r ON p.id = r.product_id GROUP BY p.id HAVING avg_rating >= 4.0;',
    'SELECT ARRAY_AGG(DISTINCT tag ORDER BY tag) AS tags FROM post_tags WHERE post_id = 42;',
    'CREATE TABLE IF NOT EXISTS migrations (id SERIAL PRIMARY KEY, name VARCHAR(255) UNIQUE NOT NULL, executed_at TIMESTAMP DEFAULT NOW());',
    'SELECT JSON_BUILD_OBJECT("id", u.id, "name", u.name, "orders", JSON_AGG(JSON_BUILD_OBJECT("id", o.id, "total", o.total))) FROM users u JOIN orders o ON u.id = o.user_id GROUP BY u.id;',
    'GRANT SELECT, INSERT, UPDATE ON products TO app_user; REVOKE DELETE ON products FROM app_user;',
    'SELECT city, COUNT(*) AS user_count, PERCENT_RANK() OVER (ORDER BY COUNT(*)) AS percentile FROM users GROUP BY city ORDER BY user_count DESC;',
    'ALTER TABLE orders ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;',
    'SELECT STRING_AGG(name, ", " ORDER BY name) AS team_members FROM employees WHERE department_id = 5;',
    'WITH daily AS (SELECT DATE(created_at) AS day, COUNT(*) AS cnt FROM events GROUP BY day) SELECT day, cnt, SUM(cnt) OVER (ORDER BY day) AS running_total FROM daily;',
    'CREATE MATERIALIZED VIEW product_stats AS SELECT product_id, COUNT(*) AS sales, SUM(quantity * price) AS revenue FROM order_items GROUP BY product_id;',
    'SELECT * FROM products WHERE to_tsvector("english", name || " " || description) @@ plainto_tsquery("english", "wireless bluetooth");',
    'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = "status_enum") THEN CREATE TYPE status_enum AS ENUM ("active", "inactive", "pending"); END IF; END $$;',
    'SELECT u.id, u.name, ARRAY(SELECT p.name FROM purchases pu JOIN products p ON pu.product_id = p.id WHERE pu.user_id = u.id) AS purchased_products FROM users u;',
    'SELECT NTILE(4) OVER (ORDER BY salary) AS quartile, name, salary FROM employees;',
    'SELECT date, revenue, AVG(revenue) OVER (ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS moving_avg_7d FROM daily_revenue;',
    'SELECT t1.id, t1.name, t2.name AS manager FROM employees t1 LEFT JOIN employees t2 ON t1.manager_id = t2.id;',
    'TRUNCATE TABLE temp_data; VACUUM ANALYZE products; REINDEX TABLE orders;',
    'SELECT pg_size_pretty(pg_total_relation_size("orders")) AS table_size;',
    'INSERT INTO users (name, email) VALUES ("Alice", "alice@example.com") ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name, updated_at = NOW();',
    'SELECT GENERATE_SERIES(1, 12) AS month, COALESCE(SUM(total), 0) AS revenue FROM orders WHERE EXTRACT(YEAR FROM created_at) = 2026 GROUP BY month ORDER BY month;',
    'CREATE OR REPLACE FUNCTION calculate_tax(amount DECIMAL) RETURNS DECIMAL AS $$ BEGIN RETURN amount * 0.18; END; $$ LANGUAGE plpgsql;',
    'SELECT name, salary, salary - LAG(salary) OVER (ORDER BY hire_date) AS salary_diff FROM employees ORDER BY hire_date;',
    'SELECT * FROM crosstab($$SELECT department, quarter, SUM(sales) FROM sales_data GROUP BY department, quarter ORDER BY 1, 2$$) AS ct(dept TEXT, q1 NUMERIC, q2 NUMERIC, q3 NUMERIC, q4 NUMERIC);',
    'COPY users (name, email, role) FROM "/tmp/users.csv" WITH (FORMAT csv, HEADER true, DELIMITER ",");',
    'SELECT schemaname, tablename, pg_size_pretty(pg_total_relation_size(schemaname || "." || tablename)) AS size FROM pg_tables WHERE schemaname = "public" ORDER BY pg_total_relation_size(schemaname || "." || tablename) DESC;',
    'WITH deleted AS (DELETE FROM expired_tokens WHERE expires_at < NOW() RETURNING id) SELECT COUNT(*) AS deleted_count FROM deleted;',
    'SELECT id, name, created_at, ROW_NUMBER() OVER (ORDER BY created_at) AS row_num, FIRST_VALUE(name) OVER (ORDER BY created_at) AS first_user FROM users;',
  ],

  cpp: [
    '#include <iostream>\nusing namespace std;\nint main() { cout << "Hello World!"; return 0; }',
    '#include <vector>\nvector<int> v = {1, 2, 3, 4};\nfor (auto& x : v) { cout << x << " "; }',
    'class Node { public: int data; Node* next; Node(int d) : data(d), next(nullptr) {} };',
    'template<typename T> T maxVal(T a, T b) { return (a > b) ? a : b; }',
    'int binarySearch(vector<int>& arr, int target) { int lo = 0, hi = arr.size() - 1; while (lo <= hi) { int mid = lo + (hi - lo) / 2; if (arr[mid] == target) return mid; if (arr[mid] < target) lo = mid + 1; else hi = mid - 1; } return -1; }',
    'sort(v.begin(), v.end(), [](int a, int b) { return a > b; });',
    'unordered_map<string, int> mp; mp["key"] = 42; if (mp.find("key") != mp.end()) { cout << mp["key"]; }',
    'unique_ptr<int> ptr = make_unique<int>(42); shared_ptr<int> sp = make_shared<int>(99);',
    'class Stack { vector<int> s; public: void push(int x) { s.push_back(x); } int pop() { int t = s.back(); s.pop_back(); return t; } };',
    'void mergeSort(vector<int>& arr, int l, int r) { if (l >= r) return; int m = (l + r) / 2; mergeSort(arr, l, m); mergeSort(arr, m + 1, r); merge(arr, l, m, r); }',
    'try { throw runtime_error("Something went wrong"); } catch (const exception& e) { cerr << e.what() << endl; }',
    'fstream file("data.txt", ios::in | ios::out); string line; while (getline(file, line)) { cout << line << endl; }',
    'struct Point { double x, y; double distance(const Point& p) const { return sqrt(pow(x - p.x, 2) + pow(y - p.y, 2)); } };',
    'auto result = accumulate(v.begin(), v.end(), 0, [](int acc, int x) { return acc + x * x; });',
    'map<string, vector<int>> graph; graph["A"].push_back(1); graph["B"].push_back(2);',
    'thread t1([]() { cout << "Thread 1" << endl; }); thread t2([]() { cout << "Thread 2" << endl; }); t1.join(); t2.join();',
    'mutex mtx; lock_guard<mutex> lock(mtx); shared_data++;',
    'int fibonacci(int n) { if (n <= 1) return n; return fibonacci(n - 1) + fibonacci(n - 2); }',
    'priority_queue<int, vector<int>, greater<int>> minHeap; minHeap.push(42); cout << minHeap.top();',
    'class Iterator { int* ptr; public: Iterator(int* p) : ptr(p) {} int& operator*() { return *ptr; } Iterator& operator++() { ++ptr; return *this; } };',
    'constexpr int factorial(int n) { return (n <= 1) ? 1 : n * factorial(n - 1); }',
    'string_view sv = "Hello, World!"; cout << sv.substr(0, 5);',
    'optional<int> findValue(const map<string, int>& m, const string& key) { auto it = m.find(key); if (it != m.end()) return it->second; return nullopt; }',
    'variant<int, double, string> v = 3.14; cout << get<double>(v);',
    'auto [name, age] = make_pair("Alice", 30); cout << name << " is " << age;',
    'ranges::sort(v); auto filtered = v | views::filter([](int x) { return x > 5; });',
    'class Singleton { static Singleton* instance; Singleton() {} public: static Singleton* get() { if (!instance) instance = new Singleton(); return instance; } };',
    'void dfs(int node, vector<vector<int>>& adj, vector<bool>& visited) { visited[node] = true; for (int next : adj[node]) if (!visited[next]) dfs(next, adj, visited); }',
    'int dp[1001]; dp[0] = 0; dp[1] = 1; for (int i = 2; i <= n; i++) dp[i] = dp[i-1] + dp[i-2];',
    'template<typename... Args> void print(Args... args) { ((cout << args << " "), ...); }',
    'int** matrix = new int*[rows]; for (int i = 0; i < rows; i++) matrix[i] = new int[cols]();',
    'regex pattern(R"(\\d{3}-\\d{3}-\\d{4})"); smatch match; if (regex_search(str, match, pattern)) cout << match[0];',
    'class Base { virtual void speak() = 0; }; class Dog : public Base { void speak() override { cout << "Woof"; } };',
    'queue<int> q; q.push(1); q.push(2); cout << q.front(); q.pop();',
    'set<int> s = {3, 1, 4, 1, 5}; auto [it, inserted] = s.insert(9); cout << *it;',
    'chrono::steady_clock::time_point start = chrono::steady_clock::now(); doWork(); auto elapsed = chrono::steady_clock::now() - start;',
    'transform(v.begin(), v.end(), v.begin(), [](int x) { return x * 2; });',
    'bitset<8> bits(42); cout << bits; cout << bits.count();',
    'async(launch::async, []() { return compute(); }).get();',
    'any val = 42; cout << any_cast<int>(val);',
    'span<int> view(arr, 5); for (auto x : view) cout << x;',
    'enum class Direction { North, South, East, West }; Direction d = Direction::North;',
    'tuple<int, string, double> t = make_tuple(1, "hello", 3.14); auto [id, name, val] = t;',
    'array<int, 5> arr = {1, 2, 3, 4, 5}; cout << arr.size();',
    'deque<int> dq; dq.push_front(1); dq.push_back(2); cout << dq.front() << dq.back();',
    'list<int> lst = {3, 1, 4}; lst.sort(); lst.unique(); lst.reverse();',
    'static_assert(sizeof(int) == 4, "int must be 4 bytes");',
    'namespace math { constexpr double PI = 3.14159265358979; double area(double r) { return PI * r * r; } }',
    'class Matrix { double data[4][4]; Matrix operator*(const Matrix& m) const { Matrix r; for (int i = 0; i < 4; i++) for (int j = 0; j < 4; j++) { r.data[i][j] = 0; for (int k = 0; k < 4; k++) r.data[i][j] += data[i][k] * m.data[k][j]; } return r; } };',
    'void quickSort(vector<int>& a, int lo, int hi) { if (lo >= hi) return; int pivot = a[(lo + hi) / 2]; int i = lo, j = hi; while (i <= j) { while (a[i] < pivot) i++; while (a[j] > pivot) j--; if (i <= j) swap(a[i++], a[j--]); } quickSort(a, lo, j); quickSort(a, i, hi); }',
  ],

  java: [
    'public class Main { public static void main(String[] args) { System.out.println("Hello World"); } }',
    'public class User { private String name; private int age; public User(String name, int age) { this.name = name; this.age = age; } public String getName() { return name; } }',
    'List<String> names = new ArrayList<>(); names.add("Alice"); names.add("Bob"); names.stream().filter(n -> n.startsWith("A")).forEach(System.out::println);',
    'Map<String, Integer> map = new HashMap<>(); map.put("key", 42); int val = map.getOrDefault("key", 0);',
    'try (BufferedReader reader = new BufferedReader(new FileReader("file.txt"))) { String line; while ((line = reader.readLine()) != null) System.out.println(line); }',
    'interface Printable { void print(); } class Document implements Printable { @Override public void print() { System.out.println("Printing..."); } }',
    'public record Point(double x, double y) { public double distance(Point p) { return Math.sqrt(Math.pow(x - p.x(), 2) + Math.pow(y - p.y(), 2)); } }',
    'CompletableFuture<String> future = CompletableFuture.supplyAsync(() -> fetchData()).thenApply(data -> process(data));',
    '@RestController @RequestMapping("/api") public class UserController { @GetMapping("/users") public List<User> getUsers() { return userService.findAll(); } }',
    'Optional<User> user = repository.findById(id); user.ifPresentOrElse(u -> process(u), () -> throw new NotFoundException());',
    'var numbers = List.of(1, 2, 3, 4, 5); int sum = numbers.stream().reduce(0, Integer::sum);',
    'public sealed interface Shape permits Circle, Rectangle {} record Circle(double radius) implements Shape {} record Rectangle(double w, double h) implements Shape {}',
    'Pattern pattern = Pattern.compile("\\\\d+"); Matcher matcher = pattern.matcher(input); while (matcher.find()) System.out.println(matcher.group());',
    'ExecutorService executor = Executors.newFixedThreadPool(4); Future<Integer> result = executor.submit(() -> compute()); executor.shutdown();',
    'public enum Season { SPRING, SUMMER, AUTUMN, WINTER; public boolean isWarm() { return this == SPRING || this == SUMMER; } }',
    'class Stack<T> { private List<T> items = new ArrayList<>(); public void push(T item) { items.add(item); } public T pop() { return items.remove(items.size() - 1); } }',
    '@Entity @Table(name = "users") public class User { @Id @GeneratedValue private Long id; @Column(nullable = false) private String name; @Column(unique = true) private String email; }',
    'int[] sorted = Arrays.stream(arr).sorted().toArray(); Map<Integer, Long> freq = Arrays.stream(arr).boxed().collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));',
    'public class Singleton { private static volatile Singleton instance; private Singleton() {} public static Singleton getInstance() { if (instance == null) { synchronized (Singleton.class) { if (instance == null) instance = new Singleton(); } } return instance; } }',
    'public abstract class Animal { protected String name; public abstract void speak(); public void eat() { System.out.println(name + " is eating"); } }',
    'Path path = Paths.get("data.txt"); List<String> lines = Files.readAllLines(path); Files.write(Paths.get("output.txt"), lines);',
    'Connection conn = DriverManager.getConnection(url, user, pass); PreparedStatement stmt = conn.prepareStatement("SELECT * FROM users WHERE id = ?"); stmt.setInt(1, userId);',
    'public int binarySearch(int[] arr, int target) { int lo = 0, hi = arr.length - 1; while (lo <= hi) { int mid = lo + (hi - lo) / 2; if (arr[mid] == target) return mid; else if (arr[mid] < target) lo = mid + 1; else hi = mid - 1; } return -1; }',
    'class LinkedList<T> { Node<T> head; class Node<T> { T data; Node<T> next; Node(T d) { data = d; } } void add(T data) { Node<T> node = new Node<>(data); node.next = head; head = node; } }',
    'ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1); scheduler.scheduleAtFixedRate(() -> checkHealth(), 0, 30, TimeUnit.SECONDS);',
    'ObjectMapper mapper = new ObjectMapper(); String json = mapper.writeValueAsString(user); User parsed = mapper.readValue(json, User.class);',
    'public void quickSort(int[] arr, int lo, int hi) { if (lo < hi) { int pivot = partition(arr, lo, hi); quickSort(arr, lo, pivot - 1); quickSort(arr, pivot + 1, hi); } }',
    'ReentrantLock lock = new ReentrantLock(); lock.lock(); try { sharedResource++; } finally { lock.unlock(); }',
    'BlockingQueue<Task> queue = new LinkedBlockingQueue<>(); queue.put(new Task()); Task task = queue.take();',
    'ConcurrentHashMap<String, Integer> map = new ConcurrentHashMap<>(); map.compute("key", (k, v) -> v == null ? 1 : v + 1);',
    'WebClient client = WebClient.create("https://api.example.com"); Mono<User> user = client.get().uri("/users/{id}", id).retrieve().bodyToMono(User.class);',
    'assertThat(result).isNotNull().hasSize(3).contains("Alice"); assertThrows(IllegalArgumentException.class, () -> process(null));',
    'var result = switch (day) { case MONDAY, FRIDAY -> "Work"; case SATURDAY, SUNDAY -> "Rest"; default -> "Midweek"; };',
    'Stream.iterate(0, n -> n + 1).limit(10).map(n -> n * n).forEach(System.out::println);',
    'String text = """ { "name": "Alice", "age": 30, "city": "NYC" } """;',
    '@FunctionalInterface interface Transformer<T, R> { R transform(T input); }',
    'PriorityQueue<Integer> minHeap = new PriorityQueue<>(); minHeap.offer(42); int top = minHeap.poll();',
    'TreeMap<String, Integer> tm = new TreeMap<>(); tm.put("apple", 1); String first = tm.firstKey(); String last = tm.lastKey();',
    'public static <T extends Comparable<T>> T max(T a, T b) { return a.compareTo(b) > 0 ? a : b; }',
    'AtomicInteger counter = new AtomicInteger(0); int val = counter.incrementAndGet();',
    'Socket socket = new Socket("localhost", 8080); PrintWriter out = new PrintWriter(socket.getOutputStream(), true); out.println("Hello Server");',
    'MessageDigest md = MessageDigest.getInstance("SHA-256"); byte[] hash = md.digest(input.getBytes(StandardCharsets.UTF_8));',
    'Duration duration = Duration.between(start, end); LocalDateTime now = LocalDateTime.now(); DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");',
    'HttpClient client = HttpClient.newHttpClient(); HttpRequest request = HttpRequest.newBuilder().uri(URI.create(url)).GET().build(); HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());',
    'IntStream.rangeClosed(1, 100).filter(n -> n % 2 == 0).mapToObj(n -> n + " ").forEach(System.out::print);',
    'public class Builder { private String name; private int age; public Builder name(String n) { name = n; return this; } public Builder age(int a) { age = a; return this; } public User build() { return new User(name, age); } }',
    'Properties props = new Properties(); props.load(new FileInputStream("config.properties")); String host = props.getProperty("db.host", "localhost");',
    'Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding"); cipher.init(Cipher.ENCRYPT_MODE, secretKey); byte[] encrypted = cipher.doFinal(plaintext);',
    'ServiceLoader<Plugin> plugins = ServiceLoader.load(Plugin.class); for (Plugin p : plugins) p.execute();',
    'Class<?> clazz = Class.forName("com.example.MyClass"); Method method = clazz.getDeclaredMethod("process"); method.invoke(clazz.getDeclaredConstructor().newInstance());',
  ],

  rust: [
    'fn main() { let message = String::from("Hello"); println!("{}", message); }',
    'fn add(a: i32, b: i32) -> i32 { a + b }',
    'let mut v: Vec<i32> = vec![1, 2, 3]; v.push(4); let sum: i32 = v.iter().sum();',
    'enum Result<T, E> { Ok(T), Err(E) }',
    'struct User { name: String, age: u32 } impl User { fn new(name: &str, age: u32) -> Self { User { name: name.to_string(), age } } }',
    'fn largest<T: PartialOrd>(list: &[T]) -> &T { let mut largest = &list[0]; for item in list { if item > largest { largest = item; } } largest }',
    'use std::collections::HashMap; let mut map = HashMap::new(); map.insert("key", 42); if let Some(v) = map.get("key") { println!("{}", v); }',
    'match value { 1 => println!("one"), 2 | 3 => println!("two or three"), 4..=9 => println!("four to nine"), _ => println!("other") }',
    'fn read_file(path: &str) -> Result<String, io::Error> { let mut file = File::open(path)?; let mut contents = String::new(); file.read_to_string(&mut contents)?; Ok(contents) }',
    'trait Shape { fn area(&self) -> f64; fn perimeter(&self) -> f64; } struct Circle { radius: f64 } impl Shape for Circle { fn area(&self) -> f64 { std::f64::consts::PI * self.radius.powi(2) } fn perimeter(&self) -> f64 { 2.0 * std::f64::consts::PI * self.radius } }',
    'let handle = std::thread::spawn(|| { for i in 0..10 { println!("thread: {}", i); } }); handle.join().unwrap();',
    'use std::sync::{Arc, Mutex}; let counter = Arc::new(Mutex::new(0)); let c = Arc::clone(&counter); *c.lock().unwrap() += 1;',
    'async fn fetch_data(url: &str) -> Result<String, reqwest::Error> { let body = reqwest::get(url).await?.text().await?; Ok(body) }',
    'impl Iterator for Counter { type Item = u32; fn next(&mut self) -> Option<Self::Item> { if self.count < 5 { self.count += 1; Some(self.count) } else { None } } }',
    '#[derive(Debug, Clone, Serialize, Deserialize)] struct Config { host: String, port: u16, debug: bool }',
    'let closure = |x: i32| -> i32 { x * 2 + 1 }; let results: Vec<i32> = (0..10).map(closure).collect();',
    'enum Command { Quit, Echo(String), Move { x: i32, y: i32 }, ChangeColor(u8, u8, u8) }',
    'fn apply<F: Fn(i32) -> i32>(f: F, x: i32) -> i32 { f(x) }',
    'use std::fs; let paths = fs::read_dir("./src")?; for path in paths { println!("{:?}", path?.path()); }',
    'impl fmt::Display for Point { fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result { write!(f, "({}, {})", self.x, self.y) } }',
    'let s1 = String::from("hello"); let s2 = s1.clone(); let s3 = &s1; println!("{} {} {}", s1, s2, s3);',
    'fn first_word(s: &str) -> &str { let bytes = s.as_bytes(); for (i, &item) in bytes.iter().enumerate() { if item == b\' \' { return &s[0..i]; } } &s[..] }',
    'Box::new(5); Rc::new(5); Arc::new(5); Cell::new(5); RefCell::new(5);',
    'macro_rules! vec_of_strings { ($($x:expr),*) => { vec![$($x.to_string()),*] }; }',
    '#[cfg(test)] mod tests { use super::*; #[test] fn test_add() { assert_eq!(add(2, 3), 5); } }',
    'pub mod my_module { pub fn public_fn() {} fn private_fn() {} pub struct PublicStruct { pub field: i32 } }',
    'impl Drop for CustomResource { fn drop(&mut self) { println!("Cleaning up resource: {}", self.name); } }',
    'type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;',
    'let re = Regex::new(r"\\d{3}-\\d{4}").unwrap(); let matched = re.is_match("123-4567");',
    'use tokio::time::{sleep, Duration}; #[tokio::main] async fn main() { sleep(Duration::from_secs(1)).await; println!("Done!"); }',
    'let data: Vec<u8> = vec![72, 101, 108, 108, 111]; let text = String::from_utf8(data).unwrap();',
    'fn binary_search(arr: &[i32], target: i32) -> Option<usize> { let mut lo = 0; let mut hi = arr.len(); while lo < hi { let mid = lo + (hi - lo) / 2; match arr[mid].cmp(&target) { Ordering::Equal => return Some(mid), Ordering::Less => lo = mid + 1, Ordering::Greater => hi = mid, } } None }',
    'struct Stack<T> { elements: Vec<T> } impl<T> Stack<T> { fn new() -> Self { Stack { elements: Vec::new() } } fn push(&mut self, item: T) { self.elements.push(item); } fn pop(&mut self) -> Option<T> { self.elements.pop() } }',
    'fn process(input: &str) -> anyhow::Result<Output> { let parsed = serde_json::from_str::<Input>(input)?; let result = transform(parsed)?; Ok(result) }',
    'let (tx, rx) = mpsc::channel(); thread::spawn(move || { tx.send(42).unwrap(); }); let received = rx.recv().unwrap();',
    'impl<T: PartialOrd> BinaryTree<T> { fn insert(&mut self, value: T) { match self { BinaryTree::Empty => *self = BinaryTree::Node(value, Box::new(BinaryTree::Empty), Box::new(BinaryTree::Empty)), BinaryTree::Node(ref v, ref mut left, ref mut right) => { if value < *v { left.insert(value) } else { right.insert(value) } } } } }',
    'use serde::{Serialize, Deserialize}; #[derive(Serialize, Deserialize)] struct ApiResponse<T> { status: u16, data: T, message: String }',
    'fn fizzbuzz(n: u32) -> String { match (n % 3, n % 5) { (0, 0) => "FizzBuzz".into(), (0, _) => "Fizz".into(), (_, 0) => "Buzz".into(), _ => n.to_string() } }',
    'use std::io::{self, BufRead}; let stdin = io::stdin(); for line in stdin.lock().lines() { println!("{}", line?); }',
    'let nums = vec![1, 2, 3, 4, 5]; let evens: Vec<&i32> = nums.iter().filter(|&&x| x % 2 == 0).collect(); let doubled: Vec<i32> = nums.iter().map(|&x| x * 2).collect();',
    'impl From<String> for MyError { fn from(msg: String) -> Self { MyError { message: msg } } }',
    'const MAX_SIZE: usize = 1024; static GLOBAL_COUNT: AtomicUsize = AtomicUsize::new(0);',
    'fn measure_time<F: FnOnce() -> T, T>(f: F) -> (T, Duration) { let start = Instant::now(); let result = f(); (result, start.elapsed()) }',
    'impl<\'a> Iterator for Tokenizer<\'a> { type Item = &\'a str; fn next(&mut self) -> Option<Self::Item> { self.input = self.input.trim_start(); if self.input.is_empty() { return None; } let end = self.input.find(\' \').unwrap_or(self.input.len()); let token = &self.input[..end]; self.input = &self.input[end..]; Some(token) } }',
    'use std::path::PathBuf; let mut path = PathBuf::from("/home/user"); path.push("documents"); path.push("file.txt"); println!("{}", path.display());',
    'fn parallel_sum(data: &[i32]) -> i32 { let mid = data.len() / 2; let (left, right) = data.split_at(mid); let (l, r) = rayon::join(|| left.iter().sum::<i32>(), || right.iter().sum::<i32>()); l + r }',
    'pub trait Handler { type Output; fn handle(&self, input: &str) -> Self::Output; }',
    'let config = Config::builder().add_source(File::with_name("config")).add_source(Environment::with_prefix("APP")).build()?;',
    'fn gcd(mut a: u64, mut b: u64) -> u64 { while b != 0 { let t = b; b = a % b; a = t; } a }',
  ],

  go: [
    'package main\nimport "fmt"\nfunc main() { fmt.Println("Hello, World!") }',
    'func add(a, b int) int { return a + b }',
    'type User struct { Name string `json:"name"`; Age int `json:"age"` }',
    'slice := []int{1, 2, 3, 4, 5}; slice = append(slice, 6)',
    'for i, v := range slice { fmt.Printf("%d: %d\\n", i, v) }',
    'if err != nil { log.Fatalf("Error: %v", err) }',
    'func (u User) String() string { return fmt.Sprintf("%s (%d)", u.Name, u.Age) }',
    'ch := make(chan int, 10); go func() { ch <- 42 }(); val := <-ch',
    'http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) { fmt.Fprintf(w, "Hello") }); http.ListenAndServe(":8080", nil)',
    'data, err := json.Marshal(user); if err != nil { return err }; err = json.Unmarshal(data, &result)',
    'ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second); defer cancel()',
    'var wg sync.WaitGroup; for i := 0; i < 10; i++ { wg.Add(1); go func(n int) { defer wg.Done(); process(n) }(i) }; wg.Wait()',
    'file, err := os.Open("data.txt"); if err != nil { panic(err) }; defer file.Close(); scanner := bufio.NewScanner(file)',
    'type Handler interface { Handle(ctx context.Context, req Request) (Response, error) }',
    'func fibonacci(n int) int { if n <= 1 { return n }; return fibonacci(n-1) + fibonacci(n-2) }',
    'db, err := sql.Open("postgres", connStr); defer db.Close(); rows, err := db.Query("SELECT id, name FROM users")',
    'mux := http.NewServeMux(); mux.HandleFunc("GET /api/users", getUsers); mux.HandleFunc("POST /api/users", createUser)',
    'var mu sync.Mutex; mu.Lock(); counter++; mu.Unlock()',
    'select { case msg := <-ch1: handle(msg); case <-time.After(5 * time.Second): fmt.Println("timeout"); case <-ctx.Done(): return }',
    'func Map[T, U any](s []T, f func(T) U) []U { r := make([]U, len(s)); for i, v := range s { r[i] = f(v) }; return r }',
    'type Stack[T any] struct { items []T }; func (s *Stack[T]) Push(v T) { s.items = append(s.items, v) }',
    'err := filepath.Walk(".", func(path string, info os.FileInfo, err error) error { fmt.Println(path); return nil })',
    'resp, err := http.Get(url); defer resp.Body.Close(); body, err := io.ReadAll(resp.Body)',
    'func binarySearch(arr []int, target int) int { lo, hi := 0, len(arr)-1; for lo <= hi { mid := lo + (hi-lo)/2; if arr[mid] == target { return mid } else if arr[mid] < target { lo = mid + 1 } else { hi = mid - 1 } }; return -1 }',
    'tmpl := template.Must(template.ParseFiles("index.html")); tmpl.Execute(w, data)',
    'func middleware(next http.Handler) http.Handler { return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { log.Println(r.Method, r.URL); next.ServeHTTP(w, r) }) }',
    'type Error struct { Code int; Message string }; func (e *Error) Error() string { return fmt.Sprintf("[%d] %s", e.Code, e.Message) }',
    'flag.StringVar(&host, "host", "localhost", "server host"); flag.IntVar(&port, "port", 8080, "server port"); flag.Parse()',
    'go func() { sig := make(chan os.Signal, 1); signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM); <-sig; shutdown() }()',
    'func retry(fn func() error, attempts int, delay time.Duration) error { for i := 0; i < attempts; i++ { if err := fn(); err == nil { return nil } else if i < attempts-1 { time.Sleep(delay) } else { return err } }; return nil }',
    'cache := sync.Map{}; cache.Store("key", "value"); val, ok := cache.Load("key")',
    'encoder := json.NewEncoder(w); encoder.SetIndent("", "  "); encoder.Encode(response)',
    'r := chi.NewRouter(); r.Use(middleware.Logger); r.Get("/users/{id}", getUser); http.ListenAndServe(":3000", r)',
    'pool := &sync.Pool{New: func() interface{} { return make([]byte, 1024) }}; buf := pool.Get().([]byte); defer pool.Put(buf)',
    'func merge(left, right []int) []int { result := make([]int, 0, len(left)+len(right)); for len(left) > 0 && len(right) > 0 { if left[0] <= right[0] { result = append(result, left[0]); left = left[1:] } else { result = append(result, right[0]); right = right[1:] } }; return append(append(result, left...), right...) }',
    'type Node struct { Val int; Next *Node }; func (n *Node) Reverse() *Node { var prev *Node; curr := n; for curr != nil { next := curr.Next; curr.Next = prev; prev = curr; curr = next }; return prev }',
    'conn, err := net.Dial("tcp", "localhost:8080"); fmt.Fprintf(conn, "GET / HTTP/1.0\\r\\n\\r\\n"); response, _ := io.ReadAll(conn)',
    'reflect.TypeOf(val).Kind(); reflect.ValueOf(&val).Elem().Set(reflect.ValueOf(newVal))',
    'hash := sha256.Sum256([]byte(data)); hex := hex.EncodeToString(hash[:])',
    'log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile); log.SetOutput(os.Stderr)',
    'type Config struct { Host string `yaml:"host"`; Port int `yaml:"port"` }; viper.ReadInConfig(); viper.Unmarshal(&config)',
    'slog.Info("request", "method", r.Method, "path", r.URL.Path, "duration", elapsed)',
    'func quickSort(arr []int) []int { if len(arr) < 2 { return arr }; pivot := arr[0]; var left, right []int; for _, v := range arr[1:] { if v <= pivot { left = append(left, v) } else { right = append(right, v) } }; return append(append(quickSort(left), pivot), quickSort(right)...) }',
    'ticker := time.NewTicker(1 * time.Second); defer ticker.Stop(); for range ticker.C { checkHealth() }',
    'once := sync.Once{}; once.Do(func() { initializeExpensiveResource() })',
    'type Result[T any] struct { Value T; Err error }; func Ok[T any](v T) Result[T] { return Result[T]{Value: v} }',
    'embed.FS; //go:embed templates/* var templates embed.FS',
    'func TestAdd(t *testing.T) { got := add(2, 3); want := 5; if got != want { t.Errorf("add(2,3) = %d; want %d", got, want) } }',
    'func BenchmarkSort(b *testing.B) { for i := 0; i < b.N; i++ { sort.Ints(data) } }',
  ],

  bash: [
    '#!/bin/bash\necho "Starting build..."\nnpm i && npm run build\necho "Done!"',
    'for file in *.txt; do echo "Processing $file"; wc -l "$file"; done',
    'if [ -f "config.json" ]; then echo "Config found"; else echo "Missing config"; exit 1; fi',
    'grep -rn "TODO" src/ --include="*.ts" | wc -l',
    'find . -name "*.log" -mtime +30 -delete',
    'curl -s https://api.example.com/data | jq ".results[] | .name"',
    'tar -czf backup_$(date +%Y%m%d).tar.gz /home/user/projects/',
    'while read -r line; do echo "Line: $line"; done < input.txt',
    'docker build -t myapp:latest . && docker run -d -p 8080:3000 myapp:latest',
    'ssh user@server "cd /app && git pull && pm2 restart all"',
    'export PATH="$HOME/.local/bin:$PATH"; export NODE_ENV=production',
    'ps aux | grep node | grep -v grep | awk "{print $2}" | xargs kill -9',
    'echo "DB backup starting..." && pg_dump -U postgres mydb > backup.sql && echo "Done!"',
    'case "$1" in start) echo "Starting...";; stop) echo "Stopping...";; *) echo "Usage: $0 {start|stop}";; esac',
    'rsync -avz --progress /local/path/ user@remote:/remote/path/',
    'COUNT=$(ls -1 *.txt 2>/dev/null | wc -l); echo "Found $COUNT text files"',
    'sed -i "s/old_string/new_string/g" file.txt',
    'awk -F"," "{print $1, $3}" data.csv | sort | uniq -c | sort -rn | head -10',
    'df -h | awk "NR>1 {print $5, $6}" | sort -rn',
    'crontab -l; echo "0 2 * * * /scripts/backup.sh" | crontab -',
    'git log --oneline -10; git diff --stat HEAD~5',
    'chmod +x script.sh; chown user:group file.txt; ls -la',
    'netstat -tulpn | grep LISTEN; lsof -i :3000',
    'systemctl status nginx; systemctl restart nginx; journalctl -u nginx -f',
    'echo "$PASSWORD" | openssl enc -aes-256-cbc -salt -out encrypted.dat',
    'watch -n 5 "df -h; echo ---; free -m; echo ---; uptime"',
    'xargs -P 4 -I {} sh -c "process {}" < filelist.txt',
    'trap "echo Caught SIGINT; cleanup; exit" INT TERM',
    'cat /proc/cpuinfo | grep "model name" | head -1; free -h; uname -a',
    'du -sh */ | sort -rh | head -20',
    'parallel --jobs 8 "convert {} -resize 800x600 resized/{}" ::: *.jpg',
    'yes | apt-get install -y nginx curl vim htop tmux git',
    'tail -f /var/log/syslog | grep --line-buffered "error"',
    'diff <(sort file1.txt) <(sort file2.txt) > differences.txt',
    'mkfifo /tmp/pipe; cat /tmp/pipe | tee output.log &',
    'mysql -u root -p -e "SHOW DATABASES; SELECT COUNT(*) FROM users;"',
    'read -p "Enter your name: " NAME; echo "Hello, $NAME!"',
    'function log() { echo "[$(date +"%Y-%m-%d %H:%M:%S")] $*" >> app.log; }',
    'test -d "$DIR" || mkdir -p "$DIR"; test -w "$DIR" || { echo "Not writable"; exit 1; }',
    'zip -r archive.zip project/ -x "node_modules/*" -x ".git/*"',
    'env | sort | grep -E "^(PATH|HOME|USER|SHELL)="',
    'seq 1 100 | shuf | head -10 | sort -n',
    'timeout 30 ping -c 5 google.com || echo "Network unreachable"',
    'declare -A colors; colors[red]="#FF0000"; colors[green]="#00FF00"; echo "${colors[red]}"',
    'set -euo pipefail; IFS=$"\\n\\t"',
    'strace -f -e trace=network -p $(pgrep node) 2>&1 | head -50',
    'jq ".[] | select(.age > 30) | {name, age}" users.json',
    'openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes',
    'ffmpeg -i input.mp4 -vf scale=1280:720 -c:a copy output.mp4',
    'git stash && git pull --rebase && git stash pop && npm test',
  ],
};
