// ─── SPECIALIZED & LITERATURE CONTENT LIBRARY ───

export const SPECIALIZED_CONTENT: Record<string, string[]> = {

  story: [
    'Once upon a time in a distant land, there was a small village nested between two mountains. The villagers were known for their legendary craftsmanship in forging intricate pieces of art from metals deep within the earth. Every hundred years, a grand festival was held to showcase their greatest masterpiece to the visiting scholars from far away kingdoms.',
    'The old lighthouse keeper had been watching the sea for forty years. Every night he climbed the spiral staircase, lit the lamp, and sat by the window. He had seen storms that could swallow ships whole and calm nights where the water looked like black glass. But tonight something was different. A light blinked back at him from the horizon.',
    'Maya discovered the hidden garden behind the abandoned library on a rainy Tuesday afternoon. The gate was covered in ivy so thick she almost missed it entirely. Inside, roses still bloomed despite years of neglect, and a stone fountain quietly trickled water into a pool where golden fish swam in lazy circles.',
    'The astronaut floated weightlessly inside the station, watching Earth rotate below. She could see hurricanes forming over the ocean, city lights flickering on as night swept across continents, and the thin blue line of atmosphere that protected everything she had ever known. In that moment, she understood why they called it the overview effect.',
    'Professor Chen had spent his entire career studying a single manuscript. Written in an unknown language and found in a sealed tomb in the desert, the document had resisted every attempt at translation. Then one morning, while drinking his coffee, he noticed a pattern in the symbols that changed everything he thought he knew.',
    'The train pulled into the station at exactly midnight. No one was waiting on the platform except a young woman holding a red umbrella. She had traveled three thousand miles to meet someone she had only spoken to through letters. As the doors opened, she held her breath and stepped forward into the cold night air.',
    'Deep in the forest, there existed a tree so old that even the elders could not remember when it was young. Its trunk was wide enough for a family to live inside, and its branches reached so high they seemed to touch the clouds. Legend said that anyone who slept beneath its canopy would dream of the future.',
    'The chef had been cooking the same dish for twenty years, perfecting every detail. The sauce had to simmer for exactly four hours. The herbs had to be picked fresh that morning. The plate had to be warmed to precisely the right temperature. Tonight was different though. Tonight a food critic was sitting at table seven.',
    'Sarah found the letter tucked inside an old book at the secondhand shop. It was dated nineteen forty-two and written in beautiful cursive handwriting. The writer described the view from their window during wartime and spoke of hope in a way that made Sarah cry right there in the middle of the store.',
    'The robot was designed to paint. Its creators had programmed it with the techniques of every great master in history. It could replicate a Monet in seconds or a Picasso in minutes. But one day it produced something entirely original, a swirl of colors and shapes that no human had ever imagined, and its creators did not know what to think.',
    'The mountain climber reached the summit just as the sun broke through the clouds. She had been climbing for six days straight, surviving on dried fruit and determination. From the top she could see three countries, two rivers, and a city that looked like a toy from this height. She sat down and wept with joy.',
    'In the year twenty-one hundred, books were no longer printed on paper. Everything existed digitally, accessible through neural implants. But one collector maintained a secret library of physical books in an underground vault. People would travel from across the world just to feel the weight of a real book in their hands.',
    'The fisherman set out before dawn as he had done every morning for fifty years. His boat was small and weathered but still seaworthy. The ocean was calm today, reflecting the pink and orange colors of the sunrise. He cast his net and waited, thinking about his granddaughter who wanted to be a marine biologist.',
    'The pianist sat at the grand piano in the empty concert hall. She placed her trembling fingers on the keys and began to play. The melody filled the vast space, bouncing off marble walls and velvet seats. She was rehearsing for her final performance before retiring, and every note carried the weight of a lifetime dedicated to music.',
    'Two strangers sat across from each other on a delayed flight. One was reading a novel and the other was staring out the rain-streaked window. Neither spoke for the first hour. Then the power went out in the terminal and in the darkness they began talking. By the time the lights returned they had become friends for life.',
    'The archaeologist brushed away centuries of dust and dirt to reveal a perfectly preserved mosaic floor. The colors were still vibrant, depicting a scene of daily life in an ancient civilization. Children playing in a courtyard, merchants selling fruit, and musicians performing under a tree. It was like looking through a window into the past.',
    'The young inventor worked in her garage every night after school. She was building a device that could convert ocean waves into clean electricity. Her teachers said it was impossible for a teenager to solve what engineers had struggled with for decades. She proved them wrong on a Tuesday in March.',
    'The detective stood in the rain outside the old mansion. Every window was dark except one on the third floor where a candle flickered. The case had gone cold three years ago but a new piece of evidence had brought her back to this place. She adjusted her collar against the wind and walked toward the front door.',
    'The space colony on Mars had been established for ten years. Three thousand people lived in pressurized domes growing hydroponic vegetables and recycling every drop of water. Children born there had never seen rain or felt natural wind. But they had something Earth children did not have. Every night they watched two moons rise.',
    'The old watchmaker had repaired thousands of timepieces in his small shop on the corner. Grandfather clocks, pocket watches, and modern wristwatches all found their way to his workbench. He believed that inside every broken watch was a story of the person who wore it, and fixing the mechanism meant restoring a piece of their history.',
    'In a small coastal town, a bookshop owner discovered that every book she shelved began glowing faintly after midnight. The glow was warm and golden, like candlelight trapped between pages. She started spending her nights in the shop, reading by the light of her own inventory, discovering stories she had somehow missed before.',
    'The migrating birds arrived three weeks early that spring. The old farmer noticed first, looking up from his plow to see thousands of swallows filling the sky. His grandfather had always said early birds meant a harsh winter was coming. But these birds seemed different somehow, as if they were not fleeing from something but rushing toward it.',
    'A young girl planted a seed in her backyard and promised to water it every day. Years passed and the seed grew into a magnificent oak. She graduated, moved away, started a career, and forgot about the tree. When she returned decades later, the oak had become the largest tree in the neighborhood and children were playing in its shade.',
    'The submarine surfaced in the middle of the Arctic Ocean. Through the periscope, the captain saw something that should not have been there. An island, small and covered in green vegetation, sitting in waters that should have been nothing but ice. None of the charts showed it. None of the satellites had detected it.',
    'The violin had been silent for eighty years, locked inside a museum display case. It had once belonged to a concert master who performed for kings and queens across Europe. When a young musician was finally allowed to play it, the instrument produced a sound so beautiful that everyone in the room stopped breathing for a moment.',
    'The last bookstore in the city was closing its doors. The owner stood behind the counter one final time, looking at the empty shelves that had once held thousands of stories. Customers came throughout the day to say goodbye, each one sharing a memory of a book that had changed their life.',
    'The mapmaker spent her entire life charting territories that no one had explored. She drew coastlines from sailors descriptions, mountain ranges from travelers tales, and rivers from the direction of migrating birds. Her maps were never perfectly accurate, but they inspired generations of explorers to venture into the unknown.',
    'There was a bridge in the old town that was said to grant wishes. You had to stand in the exact center at midnight during a full moon and whisper your deepest desire into the wind. Most people thought it was just a legend. But the bridge builder who constructed it knew the truth, and she smiled every time she crossed it.',
    'The time capsule was buried in nineteen seventy-six. Inside were newspaper clippings, photographs, a popular song recorded on vinyl, and a letter addressed to whoever would open it in fifty years. When they finally dug it up, the letter read simply: We hope you are kinder than we were. We hope you found a way to be happy.',
    'The night sky observatory was built on the highest peak in the region. Scientists traveled from around the world to use its massive telescope. But it was the janitor who made the greatest discovery. Working late one evening, he looked through the eyepiece out of curiosity and noticed a pattern in the stars that the professionals had overlooked.',
    'A painter who had lost her sight continued to create art by feeling the texture of her paint on canvas. Her works became even more powerful after her blindness because she painted from memory and emotion rather than observation. Critics called her late period the most authentic body of work produced in the century.',
    'The elevator repairman found a room that no one knew existed. Behind a false wall on the thirty-seventh floor was a perfectly furnished apartment from the nineteen twenties. Dust covered everything but it was clear that someone had lived there in complete secrecy. A diary on the desk told the story of a woman who had hidden from the world.',
    'The messenger pigeon arrived at the tower with a note tied to its leg. The note contained a single word written in red ink. The kingdom had not received a message by pigeon in over a hundred years and no one could remember what the word meant. But the eldest advisor turned pale when she read it.',
    'A community garden started with a single tomato plant in an abandoned parking lot. Within a year it grew to cover the entire block. Neighbors who had never spoken to each other began sharing tools and recipes. Children learned where food comes from. The concrete jungle transformed into something green and alive and full of connection.',
    'The deep sea diver descended into the trench alone. At one thousand meters the light disappeared completely. At two thousand meters she heard sounds that science could not explain. At three thousand meters she saw something glowing in the darkness ahead. Her camera captured seventeen seconds of footage that would change marine biology forever.',
    'The codebreaker worked in silence surrounded by walls covered in equations and symbols. She had been trying to crack the cipher for three years without success. The message was intercepted during the war and was believed to contain the location of a lost treasure. On a quiet Sunday morning the pattern finally revealed itself.',
    'Rain had not fallen in the valley for three hundred days. The river was dry, the crops were dead, and the villagers were considering leaving their ancestral home. Then a child walked out into the cracked earth carrying a small drum. She began to play a rhythm her grandmother had taught her and within an hour the clouds gathered.',
    'The postman delivered letters to the same street for forty years. He knew every family, every dog, every mailbox with a sticky hinge. When he retired, the neighborhood threw him a party. Every household contributed a letter thanking him for being the most reliable person they had ever known.',
    'Two chess grandmasters sat across from each other in a silent room. The clock ticked between them. One had been world champion for a decade. The other was seventeen years old and had never lost a match. The game lasted seven hours and ended with a position so complex that computers took three days to fully analyze it.',
    'The seed vault deep inside the Arctic mountain contained samples from every known plant species on Earth. It was designed to survive any disaster. The scientist in charge walked through the frozen corridors knowing that somewhere in these shelves was the key to feeding humanity if everything else failed.',
    'An unknown artist began painting murals on the sides of buildings throughout the city. Each mural depicted a scene of community and hope. People gathered to watch them appear overnight. The identity of the artist remained a mystery for years until a grandmother in a nursing home recognized the style as her own from decades ago.',
    'The harbor master watched the last sailing ship depart from the port. It was the end of an era. Steam and diesel had replaced canvas and wind years ago, but this particular vessel had held on. Its captain was ninety years old and wanted one final voyage across the Atlantic using nothing but the forces of nature.',
    'A musician found a recording in her grandmothers attic. The tape was from nineteen sixty-three and contained a song that had never been released. The melody was haunting and beautiful. She cleaned up the audio and shared it online. Within a week it had been heard by ten million people around the world.',
    'The night watchman walked the halls of the museum after closing. He had memorized every painting, every sculpture, every artifact. Sometimes he would stand in front of a particular landscape painting and imagine himself walking into the scene. He believed the paintings remembered him too.',
    'A letter arrived at the wrong address and changed two lives forever. The recipient read someone elses mail by accident and discovered a story so compelling that she wrote back. The correspondence continued for a year before they finally met in person at a cafe downtown.',
    'The telescope captured an image from thirteen billion light years away. Scientists stared at the photograph showing the oldest light ever recorded. Somewhere in that ancient glow were the seeds of every star, every planet, and every living thing that would ever exist. The universe looked back at them across an unimaginable span of time.',
    'The blacksmith hammered the glowing metal with steady rhythmic blows. Each strike shaped the blade a little more. His apprentice watched from the corner memorizing every movement. The old man had been forging swords for fifty years and this would be his final masterpiece. He poured every lesson he had ever learned into a single perfect edge.',
    'A small cafe at the edge of the world served coffee to travelers and locals alike. The owner knew everyone by name and their usual order by heart. She had traveled the world herself before settling here and every cup she poured contained a small piece of her journey.',
    'The migration of the monarch butterflies was early this year. Millions of orange and black wings filled the sky like living confetti. Scientists tracked their journey across three thousand miles wondering how creatures with brains smaller than a pinhead could navigate with such precision.',
    'The last letter ever written by hand was displayed in a museum in the year twenty two hundred. People lined up for hours just to see real handwriting on real paper. A child pressed her face against the glass and whispered to her mother asking if people really used to communicate this way.',
  ],

  quotes: [
    '"I have not failed. I have just found 10,000 ways that won\'t work." - Thomas A. Edison',
    '"The only way to do great work is to love what you do." - Steve Jobs',
    '"In the middle of difficulty lies opportunity." - Albert Einstein',
    '"It does not matter how slowly you go as long as you do not stop." - Confucius',
    '"The best time to plant a tree was twenty years ago. The second best time is now." - Chinese Proverb',
    '"Success is not final, failure is not fatal: it is the courage to continue that counts." - Winston Churchill',
    '"Life is what happens when you are busy making other plans." - John Lennon',
    '"The greatest glory in living lies not in never falling, but in rising every time we fall." - Nelson Mandela',
    '"The future belongs to those who believe in the beauty of their dreams." - Eleanor Roosevelt',
    '"It is during our darkest moments that we must focus to see the light." - Aristotle',
    '"The only thing we have to fear is fear itself." - Franklin D. Roosevelt',
    '"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment." - Ralph Waldo Emerson',
    '"Two things are infinite: the universe and human stupidity. I am not sure about the universe." - Albert Einstein',
    '"Be the change you wish to see in the world." - Mahatma Gandhi',
    '"An unexamined life is not worth living." - Socrates',
    '"I think, therefore I am." - Rene Descartes',
    '"That which does not kill us makes us stronger." - Friedrich Nietzsche',
    '"We are what we repeatedly do. Excellence, then, is not an act, but a habit." - Aristotle',
    '"The only true wisdom is in knowing you know nothing." - Socrates',
    '"Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world." - Albert Einstein',
    '"Stay hungry, stay foolish." - Steve Jobs',
    '"Not all those who wander are lost." - J.R.R. Tolkien',
    '"The unexamined life is not worth living." - Socrates',
    '"In three words I can sum up everything I learned about life: it goes on." - Robert Frost',
    '"To live is the rarest thing in the world. Most people exist, that is all." - Oscar Wilde',
    '"You must be the change you wish to see in the world." - Mahatma Gandhi',
    '"It is never too late to be what you might have been." - George Eliot',
    '"The mind is everything. What you think you become." - Buddha',
    '"Strive not to be a success, but rather to be of value." - Albert Einstein',
    '"I have learned over the years that when one\'s mind is made up, this diminishes fear." - Rosa Parks',
    '"Everything you can imagine is real." - Pablo Picasso',
    '"Do what you can, with what you have, where you are." - Theodore Roosevelt',
    '"If you want to lift yourself up, lift up someone else." - Booker T. Washington',
    '"The purpose of our lives is to be happy." - Dalai Lama',
    '"You miss one hundred percent of the shots you never take." - Wayne Gretzky',
    '"Whether you think you can or you think you cannot, you are right." - Henry Ford',
    '"I have a dream that one day this nation will rise up and live out the true meaning of its creed." - Martin Luther King Jr.',
    '"The pen is mightier than the sword." - Edward Bulwer-Lytton',
    '"Knowledge is power." - Sir Francis Bacon',
    '"Where there is no vision, the people perish." - Proverbs 29:18',
    '"Fortune favors the bold." - Virgil',
    '"Those who dare to fail miserably can achieve greatly." - John F. Kennedy',
    '"A person who never made a mistake never tried anything new." - Albert Einstein',
    '"What lies behind us and what lies before us are tiny matters compared to what lies within us." - Ralph Waldo Emerson',
    '"The only impossible journey is the one you never begin." - Tony Robbins',
    '"Every moment is a fresh beginning." - T.S. Eliot',
    '"Turn your wounds into wisdom." - Oprah Winfrey',
    '"The way to get started is to quit talking and begin doing." - Walt Disney',
    '"If you tell the truth, you don\'t have to remember anything." - Mark Twain',
    '"Whoever is happy will make others happy too." - Anne Frank',
  ],

  scientific: [
    'photosynthesis mitochondria electromagnetism thermodynamics relativity particle organic genome',
    'quantum mechanics entropy nuclear fission catalyst oxidation reduction polymer isotope spectrum',
    'chromosome mutation evolution natural selection adaptation genetic drift speciation extinction',
    'hypothesis experiment variable control group independent dependent observation conclusion data',
    'acceleration velocity displacement momentum torque friction centripetal gravitational force energy',
    'covalent ionic metallic hydrogen bonding intermolecular forces polarity electronegativity valence',
    'photon wavelength frequency amplitude interference diffraction refraction polarization absorption',
    'ecosystem biodiversity symbiosis predation parasitism mutualism commensalism decomposition trophic',
    'tectonic plates continental drift subduction seismic volcanic magma mantle lithosphere asthenosphere',
    'neurotransmitter synapse dendrite axon myelin action potential receptor inhibitory excitatory neuron',
    'mitosis meiosis diploid haploid cytokinesis chromosomal crossing over recombination homologous pairs',
    'endoplasmic reticulum golgi apparatus lysosome ribosome vacuole chloroplast nucleus cell membrane',
    'ionization electron configuration orbital periodic table atomic number mass number isotope element',
    'kinetic potential thermal chemical electrical gravitational elastic nuclear mechanical internal',
    'deoxyribonucleic acid ribonucleic acid transcription translation codon anticodon messenger transfer',
    'centrifugal gravitational electromagnetic strong nuclear weak nuclear fundamental forces interaction',
    'biome deciduous coniferous tundra savanna tropical temperate boreal alpine aquatic terrestrial marine',
    'semiconductor conductor insulator superconductor diode transistor integrated circuit microprocessor',
    'metabolism anabolism catabolism enzyme substrate activation energy cofactor inhibitor catalyst',
    'magnetic field electric field gravitational field scalar vector tensor gradient divergence curl',
    'osmosis diffusion active transport passive transport concentration gradient equilibrium homeostasis',
    'sedimentary igneous metamorphic erosion weathering deposition stratigraphy paleontology fossilization',
    'pathogen antibody antigen immune response vaccination phagocytosis lymphocyte macrophage inflammation',
    'stoichiometry molarity concentration titration precipitation neutralization combustion decomposition',
    'heliocentric geocentric astronomical unit light year parsec parallax redshift blueshift expansion',
    'recessive dominant codominant incomplete dominance phenotype genotype allele locus heterozygous',
    'inertia equilibrium angular momentum conservation rotational translational linear acceleration',
    'capacitance inductance impedance resistance ohm volt ampere watt joule coulomb farad henry',
    'exothermic endothermic enthalpy entropy gibbs free energy spontaneous reversible irreversible',
    'chromatography spectroscopy electrophoresis centrifugation distillation filtration crystallization',
    'prokaryotic eukaryotic archaebacteria eubacteria protista fungi plantae animalia domain kingdom',
    'convection conduction radiation thermal equilibrium specific heat latent heat phase transition',
    'doppler effect resonance standing wave harmonic overtone fundamental frequency wavelength period',
    'hydrocarbon alkane alkene alkyne aromatic functional group isomer stereoisomer conformational',
    'continental shelf abyssal plain oceanic trench mid ocean ridge hydrothermal vent bioluminescence',
    'standard deviation variance mean median mode correlation regression probability distribution normal',
    'superposition entanglement wave function collapse measurement uncertainty complementarity observer',
    'plate boundary convergent divergent transform subduction zone earthquake epicenter seismograph',
    'electromagnetic spectrum radio microwave infrared visible ultraviolet x-ray gamma ray wavelength',
    'polymerase chain reaction gel electrophoresis restriction enzyme plasmid vector cloning sequencing',
    'atmospheric pressure barometer humidity precipitation dew point condensation evaporation convection',
    'carnivore herbivore omnivore detritivore autotroph heterotroph producer consumer decomposer primary',
    'stellar evolution main sequence red giant white dwarf neutron star black hole supernova nebula protostar',
    'alternating current direct current transformer generator motor electromagnetic induction faraday',
    'amino acid polypeptide protein quaternary tertiary secondary primary structure denaturation folding',
    'continental glacier alpine glacier moraine till drumlin esker kettle outwash plain glacial erratic',
    'relative humidity absolute humidity saturation vapor pressure cloud formation precipitation cycle',
    'nuclear fusion nuclear fission binding energy mass defect critical mass chain reaction moderator',
    'phylogenetic taxonomy cladistics monophyletic polyphyletic paraphyletic morphological molecular',
    'longitudinal transverse mechanical electromagnetic compression rarefaction amplitude crest trough',
  ],

  medical: [
    'cardiovascular neurological respiratory antibiotics intravenous surgery anesthesia plasma pathogen',
    'diagnosis prognosis symptom syndrome etiology pathology epidemiology prevalence incidence morbidity',
    'hypertension hypotension tachycardia bradycardia arrhythmia fibrillation atrial ventricular systolic',
    'hematology oncology nephrology pulmonology gastroenterology endocrinology dermatology ophthalmology',
    'magnetic resonance imaging computed tomography ultrasound radiograph fluoroscopy positron emission',
    'antibiotic antiviral antifungal antipyretic analgesic antihistamine corticosteroid immunosuppressant',
    'inflammation infection sepsis abscess cellulitis meningitis pneumonia bronchitis pharyngitis otitis',
    'fracture dislocation sprain strain contusion laceration abrasion avulsion puncture incision excision',
    'insulin glucagon thyroid parathyroid adrenal pituitary hypothalamus cortisol epinephrine testosterone',
    'hemoglobin leukocyte erythrocyte thrombocyte platelet plasma serum fibrinogen coagulation hemostasis',
    'appendectomy cholecystectomy colectomy mastectomy thyroidectomy hysterectomy nephrectomy splenectomy',
    'electrocardiogram echocardiogram catheterization angioplasty stent bypass grafting defibrillation',
    'cerebrovascular accident transient ischemic attack hemorrhage thrombosis embolism aneurysm stenosis',
    'benign malignant metastasis carcinoma sarcoma lymphoma leukemia melanoma adenoma polyp neoplasm tumor',
    'ventilator intubation tracheostomy bronchoscopy spirometry oximetry capnography arterial blood gas',
    'anaphylaxis autoimmune immunodeficiency allergen sensitization desensitization hypersensitivity',
    'arthritis osteoporosis scoliosis herniated disc tendinitis bursitis fibromyalgia rheumatoid gout',
    'diabetes mellitus hyperglycemia hypoglycemia insulin resistance metabolic syndrome ketoacidosis',
    'renal failure dialysis nephritis pyelonephritis glomerulonephritis proteinuria hematuria creatinine',
    'gastroesophageal reflux disease peptic ulcer inflammatory bowel disease irritable bowel syndrome',
    'asthma chronic obstructive pulmonary disease emphysema bronchiectasis pulmonary fibrosis pleurisy',
    'myocardial infarction angina pectoris congestive heart failure cardiomyopathy pericarditis endocarditis',
    'seizure epilepsy multiple sclerosis parkinson disease alzheimer disease dementia neuropathy radiculopathy',
    'laceration suture debridement irrigation immobilization reduction splint cast traction rehabilitation',
    'prescription dosage contraindication adverse reaction pharmacokinetics pharmacodynamics bioavailability',
    'triage emergency department intensive care unit operating room recovery room discharge admission',
    'vital signs blood pressure heart rate respiratory rate temperature oxygen saturation consciousness',
    'auscultation palpation percussion inspection assessment intervention documentation referral follow up',
    'prophylaxis vaccination immunization quarantine isolation decontamination sterilization disinfection',
    'differential diagnosis clinical presentation chief complaint history physical examination laboratory',
    'congenital acquired hereditary genetic chromosomal autosomal recessive dominant sex linked mutation',
    'anterior posterior medial lateral superior inferior proximal distal superficial deep bilateral',
    'edema cyanosis jaundice pallor diaphoresis dyspnea orthopnea tachypnea bradypnea apnea stridor',
    'palliative curative preventive rehabilitative diagnostic therapeutic supportive conservative surgical',
    'obstetrics gynecology pediatrics geriatrics psychiatry radiology pathology anesthesiology cardiology',
    'transfusion transplantation donation compatibility crossmatch rejection immunosuppression graft',
    'abscess biopsy aspiration drainage debridement excision cauterization cryotherapy laser therapy',
    'ambulatory outpatient inpatient acute chronic subacute terminal convalescent rehabilitative hospice',
    'compliance adherence informed consent confidentiality privacy autonomy beneficence nonmaleficence',
    'pandemic epidemic endemic outbreak cluster surveillance contact tracing quarantine vaccination herd',
    'stress fracture overuse injury repetitive strain carpal tunnel syndrome plantar fasciitis shin splint',
    'cerebral cortex hippocampus amygdala thalamus hypothalamus cerebellum brainstem spinal cord peripheral',
    'systemic lupus erythematosus rheumatoid arthritis scleroderma dermatomyositis polymyalgia rheumatica',
    'complete blood count comprehensive metabolic panel lipid panel thyroid function coagulation studies',
    'magnetic resonance angiography computed tomography angiography digital subtraction angiography doppler',
    'anticoagulant thrombolytic antiplatelet vasodilator vasoconstrictor diuretic beta blocker calcium channel',
    'urinalysis culture sensitivity colony forming unit minimum inhibitory concentration susceptibility',
    'emergent urgent semi urgent non urgent resuscitation stabilization definitive care transport triage',
    'perioperative preoperative intraoperative postoperative anesthesia sedation analgesic monitoring recovery',
    'electroencephalogram electromyography nerve conduction study evoked potential polysomnography biofeedback',
  ],

  legal: [
    'jurisdiction affidavit deposition litigation subpoena liability defendant plaintiff testimony verdict',
    'arbitration mediation negotiation settlement compensation damages injunction restraining order motion',
    'constitutional amendment statute regulation ordinance precedent case law common law statutory law',
    'due process equal protection habeas corpus double jeopardy self incrimination right to counsel jury',
    'breach of contract consideration promissory estoppel specific performance liquidated damages warranty',
    'negligence duty of care proximate cause foreseeability contributory comparative assumption of risk',
    'intellectual property patent trademark copyright trade secret infringement licensing royalty fair use',
    'criminal defendant prosecution defense beyond reasonable doubt preponderance probable cause indictment',
    'appellate court supreme court district court magistrate federal circuit bankruptcy probate family court',
    'discovery interrogatories request for production request for admission subpoena duces tecum deposition',
    'tort intentional negligent strict liability product liability premises liability medical malpractice',
    'fiduciary duty agent principal trustee beneficiary escrow power of attorney guardian conservator',
    'property law real estate conveyance deed title mortgage lien easement eminent domain zoning adverse',
    'corporate law articles of incorporation bylaws shareholder fiduciary duty merger acquisition dissolution',
    'employment law wrongful termination discrimination harassment whistleblower collective bargaining union',
    'immigration law visa naturalization deportation asylum refugee green card citizenship permanent resident',
    'environmental law pollution regulation compliance enforcement remediation conservation sustainability',
    'tax law income tax estate tax capital gains deduction exemption filing audit assessment liability',
    'evidence admissible hearsay relevance prejudicial probative weight credibility authentication chain',
    'contract offer acceptance consideration capacity legality writing performance discharge breach remedy',
    'plea bargain arraignment preliminary hearing grand jury indictment information arraignment sentencing',
    'bail bond surety recognizance parole probation supervised release community service restitution fine',
    'class action derivative suit interpleader intervention joinder consolidation severance bifurcation stay',
    'statute of limitations statute of repose laches estoppel waiver ratification novation rescission',
    'sovereign immunity qualified immunity absolute privilege conditional privilege diplomatic immunity',
    'search and seizure warrant probable cause reasonable suspicion exclusionary rule fruit of poisonous tree',
    'freedom of speech assembly religion press petition establishment clause free exercise clause separation',
    'equal protection under law due process substantive procedural rational basis strict scrutiny intermediate',
    'legislative executive judicial separation of powers checks and balances bicameral veto override impeach',
    'bankruptcy chapter seven chapter eleven chapter thirteen debtor creditor trustee discharge automatic stay',
    'antitrust monopoly restraint of trade price fixing merger acquisition horizontal vertical agreement',
    'administrative law agency rulemaking adjudication notice and comment judicial review arbitrary capricious',
    'international law treaty convention protocol sovereignty jurisdiction extraterritorial diplomatic',
    'civil rights equal opportunity affirmative action protected class discrimination disparate impact',
    'real property personal property tangible intangible fixture chattel chose in action possessory interest',
    'criminal procedure arrest booking arraignment bail preliminary hearing grand jury trial sentencing appeal',
    'family law marriage dissolution custody support adoption paternity prenuptial postnuptial separation',
    'securities law registration exemption prospectus insider trading fraud manipulation disclosure material',
    'legal ethics attorney client privilege conflict of interest competence diligence confidentiality loyalty',
    'alternative dispute resolution mediation arbitration negotiation conciliation facilitation mini trial',
    'landlord tenant lease eviction security deposit habitability quiet enjoyment constructive actual notice',
    'wills trusts estates probate intestate testamentary capacity executor administrator personal representative',
    'maritime admiralty jurisdiction salvage general average collision limitation of liability maintenance cure',
    'consumer protection unfair deceptive practices warranty express implied merchantability fitness purpose',
    'labor law minimum wage overtime exempt classification independent contractor employee benefits leave',
    'zoning ordinance variance conditional use permit nonconforming use comprehensive plan subdivision plat',
    'insurance law premium deductible coverage exclusion endorsement subrogation indemnity insurable interest',
    'banking law regulation compliance audit examination enforcement consent order cease and desist penalty',
    'cyber law data privacy security breach notification consent collection processing transfer retention',
    'construction law mechanic lien bond performance payment indemnification warranty defect delay claim',
  ],

  dictionary: [
    'Ebullient: cheerful and full of energy. Fastidious: very attentive to and concerned about accuracy and detail.',
    'Ineffable: too great or extreme to be expressed or described in words. Ephemeral: lasting for a very short time.',
    'Quintessential: representing the most perfect or typical example of a quality or class of things.',
    'Surreptitious: kept secret, especially because it would not be approved of. Clandestine: kept secret or hidden.',
    'Ubiquitous: present, appearing, or found everywhere. Pervasive: spreading widely throughout an area or group.',
    'Mellifluous: sweet sounding and pleasant to hear. Euphonious: pleasing to the ear, harmonious.',
    'Serendipity: the occurrence of events by chance in a happy or beneficial way. Fortune: luck, chance.',
    'Perspicacious: having a ready insight into and understanding of things. Astute: showing sharp judgment.',
    'Loquacious: tending to talk a great deal, talkative. Garrulous: excessively talkative in a rambling way.',
    'Sanguine: optimistic or positive, especially in difficult situations. Buoyant: cheerful, optimistic.',
    'Magnanimous: very generous or forgiving, especially toward a rival. Benevolent: well meaning and kindly.',
    'Obsequious: obedient or attentive to an excessive degree. Servile: having or showing excessive willingness.',
    'Pragmatic: dealing with things sensibly and realistically. Utilitarian: designed to be useful or practical.',
    'Recalcitrant: having an obstinately uncooperative attitude. Intractable: hard to control or deal with.',
    'Vicissitude: a change of circumstances or fortune, typically one that is unwelcome or unpleasant.',
    'Pernicious: having a harmful effect, especially in a gradual or subtle way. Deleterious: causing harm.',
    'Cacophony: a harsh discordant mixture of sounds. Dissonance: a tension or clash resulting from discord.',
    'Anachronism: a thing belonging to a period other than that in which it exists. Archaic: very old or outdated.',
    'Propensity: an inclination or natural tendency to behave in a particular way. Predilection: preference.',
    'Egregious: outstandingly bad, shocking. Flagrant: conspicuously or obviously offensive.',
    'Insidious: proceeding in a gradual, subtle way but with harmful effects. Treacherous: guilty of betrayal.',
    'Ambivalent: having mixed feelings or contradictory ideas about something. Equivocal: open to interpretation.',
    'Exacerbate: make something that is already bad even worse. Aggravate: make more serious or severe.',
    'Superfluous: unnecessary, especially through being more than enough. Redundant: not or no longer needed.',
    'Tenacious: tending to keep a firm hold of something. Persistent: continuing firmly in a course of action.',
    'Ameliorate: make something bad or unsatisfactory better. Mitigate: make less severe, serious, or painful.',
    'Erudite: having or showing great knowledge or learning. Scholarly: involving or relating to serious study.',
    'Parsimonious: unwilling to spend money or use resources. Frugal: sparing or economical with money.',
    'Equanimity: mental calmness, composure, and evenness of temper. Serenity: the state of being calm.',
    'Juxtaposition: the fact of two things being seen or placed close together for contrasting effect.',
    'Capricious: given to sudden and unaccountable changes of mood or behavior. Fickle: changing frequently.',
    'Languorous: the state of feeling pleasantly tired or inert. Lethargic: affected by lack of energy.',
    'Audacious: showing a willingness to take surprisingly bold risks. Intrepid: fearless and adventurous.',
    'Perfunctory: an action carried out with a minimum of effort or reflection. Cursory: hasty and superficial.',
    'Cogent: clear, logical, and convincing. Compelling: evoking interest or attention in a powerfully way.',
    'Discerning: having or showing good judgment. Discriminating: having or showing refined taste or judgment.',
    'Acquiesce: accept something reluctantly but without protest. Capitulate: cease to resist, surrender.',
    'Conundrum: a confusing and difficult problem or question. Enigma: a person or thing that is mysterious.',
    'Fortuitous: happening by accident or chance rather than design. Coincidental: resulting from coincidence.',
    'Impervious: not allowing fluid to pass through. Invulnerable: impossible to harm or damage.',
    'Myriad: a countless or extremely great number. Multitude: a large number of people or things.',
    'Nefarious: wicked or criminal. Depraved: morally corrupt.',
    'Paradox: a seemingly absurd or self-contradictory statement or proposition. Oxymoron: a figure of speech.',
    'Quintessence: the most perfect or typical example of a quality or class. Epitome: a person or thing.',
    'Repudiate: refuse to accept or be associated with. Renounce: formally declare ones abandonment of.',
    'Sagacious: having or showing keen mental discernment and good judgment. Sapient: wise, or attempting to.',
    'Truculent: eager or quick to argue or fight. Bellicose: demonstrating aggression and willingness to fight.',
    'Unctuous: excessively or ingratiatingly flattering. Sycophantic: behaving in a servile way.',
    'Verisimilitude: the appearance of being true or real. Plausibility: the quality of seeming reasonable.',
    'Zeitgeist: the defining spirit or mood of a particular period of history. Milieu: a persons social environment.',
  ],

  paragraphs: [
    'Endurance is key. When you type for longer durations, you train your muscle memory to become resilient against physical fatigue and minor distractions. The goal is not just speed but sustained accuracy over time. Professional typists maintain their form even after hours of continuous work, and this kind of stamina is built through deliberate extended practice sessions.',
    'The art of touch typing involves training each finger to take responsibility for its designated keys. The home row serves as the anchor position from which all other keys are reached. With proper technique, your eyes never need to leave the screen, allowing your brain to focus on composing thoughts rather than hunting for individual letters.',
    'In the modern digital workspace, typing speed directly correlates with productivity. Studies show that increasing your typing speed from forty words per minute to eighty words per minute effectively doubles your written output. This improvement compounds over a career spanning decades, potentially saving thousands of hours.',
    'Accuracy is more important than speed when developing typing skills. A fast typist who makes many errors spends significant time correcting mistakes, which often negates the benefit of their raw speed. Focus on hitting the correct keys consistently and speed will naturally follow with continued practice.',
    'The history of the keyboard layout dates back to the eighteen seventies when Christopher Latham Sholes designed the QWERTY arrangement. Contrary to popular belief, the layout was not designed to slow typists down. Instead it was arranged to prevent mechanical typewriter jams by separating commonly paired letters onto opposite sides of the keyboard.',
    'Ergonomics plays a crucial role in typing performance and longevity. Proper hand positioning, wrist alignment, and chair height all contribute to faster typing and reduced risk of repetitive strain injuries. Many professional typists use split keyboards and ergonomic setups to maintain their health over long careers.',
    'The cognitive load of typing decreases dramatically as motor skills become automated through practice. When beginning typists think about each individual key press they are using conscious attention. Expert typists have pushed this process into procedural memory, freeing their conscious mind for higher-level thinking.',
    'Programming requires a unique typing skillset that goes beyond traditional prose typing. Developers must be proficient with special characters, brackets, semicolons, and operators that rarely appear in everyday writing. Code typing practice specifically targets these characters to build fluency with programming syntax.',
    'The transition from two-finger pecking to proper touch typing can be frustrating initially. New typists often experience a temporary decrease in speed as they learn the correct finger positions. However this investment pays off exponentially as muscle memory develops, eventually resulting in speeds that pecking could never achieve.',
    'Consistent daily practice of even fifteen to thirty minutes produces better results than sporadic marathon sessions. The brain consolidates motor skills during rest periods between practice sessions, making short frequent practices more effective for long-term skill development than occasional intense efforts.',
    'Modern typing tests measure more than just words per minute. They track consistency, error patterns, problem keys, and fatigue curves. Advanced analysis can identify specific weaknesses such as particular finger combinations that cause slowdowns, allowing targeted practice for maximum improvement.',
    'The concept of flow state applies directly to typing. When a typist reaches the point where the keyboard disappears from conscious awareness and words simply appear on screen as fast as they are thought, they have achieved a form of flow that is both productive and deeply satisfying to experience.',
    'International keyboard layouts vary significantly across languages and regions. The AZERTY layout is common in France while QWERTZ is used in Germany. Each layout reflects the frequency of characters in the respective language, optimizing common letter combinations for faster input.',
    'Voice recognition technology has improved dramatically but has not replaced keyboard typing for most professional work. The precision and editability of typed text, combined with the ability to work quietly in shared spaces, ensures that keyboard proficiency remains an essential professional skill for decades to come.',
    'Competitive typing has grown into a recognized sport with dedicated communities and tournaments. Top competitive typists achieve speeds exceeding two hundred words per minute with near perfect accuracy, demonstrating the remarkable potential of human motor skill development through dedicated practice.',
    'The relationship between thinking speed and typing speed creates an interesting dynamic. When your typing speed matches or exceeds your thinking speed for a particular task, the mechanical act of typing no longer creates a bottleneck. This is the ideal state for writing, coding, and other text-based creative work.',
    'Proper breathing during typing is often overlooked but plays a significant role in performance. Shallow breathing leads to tension in the shoulders and arms, which slows down finger movement. Deep regular breathing promotes relaxation and allows for more fluid natural typing motion over extended periods.',
    'Eye strain is a common complaint among heavy typists. The twenty-twenty-twenty rule suggests looking at something twenty feet away for twenty seconds every twenty minutes. This simple practice reduces eye fatigue and helps maintain focus during long typing sessions throughout the workday.',
    'The development of mechanical keyboards has introduced a new dimension to the typing experience. Different switch types offer varying levels of tactile feedback, actuation force, and sound. Many typists find that the right keyboard significantly impacts their comfort speed and overall enjoyment of typing.',
    'Building a consistent typing routine is similar to athletic training. Like physical exercise, typing practice should include warm up exercises, focused drills on weak areas, and gradual progression in difficulty. Recovery periods are equally important to prevent overuse injuries and mental fatigue from diminishing returns.',
    'The psychological aspect of typing cannot be ignored. Performance anxiety during timed tests can reduce typing speed by ten to twenty percent compared to relaxed practice sessions. Learning to maintain composure under pressure is an important skill that transfers to many professional situations beyond typing.',
    'Cross-training between different types of content improves overall typing ability. A typist who practices with prose, code, numbers, and special characters develops a more versatile skillset than one who only practices with standard English text. This variety also keeps practice sessions engaging and mentally stimulating.',
    'The evolution of the typing profession spans from dedicated typists in typing pools to the modern reality where nearly every knowledge worker types throughout their day. What was once a specialized craft has become a universal skill that underpins much of modern professional work.',
    'Sleep quality directly affects typing performance. Research shows that well-rested typists not only type faster but also make fewer errors compared to their sleep-deprived counterparts. The consolidation of motor memories during sleep is essential for translating daily practice into permanent skill improvement.',
    'The concept of deliberate practice, popularized by researcher Anders Ericsson, applies perfectly to typing improvement. Simply typing more does not guarantee improvement. Focused attention on specific weaknesses, immediate feedback on errors, and progressive difficulty are all necessary components of effective typing practice.',
    'Digital communication has made typing the primary method of human interaction in many contexts. Emails, instant messages, social media posts, and collaborative documents all rely on typed text. The ability to express thoughts quickly and accurately through typing has become as fundamental as speaking clearly.',
    'The future of text input may involve new technologies such as brain computer interfaces and gesture recognition. However, keyboard typing is likely to remain dominant for professional applications for many years due to its precision, speed, and the massive existing infrastructure built around keyboard input.',
    'Temperature affects typing performance in subtle ways. Cold hands type slower due to reduced blood flow and finger flexibility. Maintaining a comfortable room temperature and keeping hands warm before practice sessions can result in measurably better typing performance across all metrics.',
    'The muscle memory developed through typing practice is remarkably durable. Even after extended breaks from regular practice, experienced typists can usually return to near their peak performance within a few sessions. This persistence of motor skills is a testament to how deeply the brain encodes frequently practiced movements.',
    'Mindful typing is an emerging practice that combines typing exercises with meditation principles. Practitioners focus entirely on the physical sensation of each keystroke, the rhythm of their typing, and their breathing pattern. This approach not only improves typing skills but also promotes mental clarity and stress reduction.',
    'Typography and formatting knowledge enhances the value of fast typing skills. Knowing when to use bold, italic, headers, and lists transforms raw typing speed into effective communication. A skilled typist who understands document structure produces higher quality work than a fast typist who ignores formatting.',
    'The impact of typing posture on long-term health cannot be overstated. Carpal tunnel syndrome and other repetitive strain injuries affect millions of people annually. Proper ergonomic setup including monitor height, keyboard angle, and chair support can prevent these conditions while improving typing comfort and speed.',
    'Group typing exercises and competitions create a social dimension to skill development. The motivation provided by friendly competition and the accountability of practicing with others often leads to faster improvement than solo practice. Many online platforms now offer real-time multiplayer typing races.',
    'The integration of typing practice into educational curricula has become increasingly important. Students who develop strong typing skills early have a significant advantage in completing assignments, taking notes, and communicating digitally. Schools that invest in typing education report improved academic outcomes across all subjects.',
    'Customizing keyboard shortcuts for frequently used applications can dramatically increase productivity beyond raw typing speed. Learning application-specific shortcuts for text editors, email clients, and web browsers multiplies the efficiency gains from fast typing by reducing the need for mouse interactions.',
    'The rhythm of typing is often compared to music. Skilled typists develop a characteristic cadence that reflects their personal typing style. Some type in rapid bursts followed by brief pauses, while others maintain a steady consistent tempo. Finding your natural rhythm is an important step in developing a comfortable and sustainable typing practice.',
    'Error correction strategies vary among expert typists. Some prefer to immediately backspace and correct errors as they occur, while others push through to the end of a thought and then review. Research suggests that the optimal strategy depends on the type of work being performed, with immediate correction being better for final drafts and deferred correction better for brainstorming.',
    'The environmental factors affecting typing performance extend beyond physical comfort. Noise levels, lighting conditions, and even the color temperature of ambient light can influence concentration and by extension typing accuracy and speed. Creating an optimized typing environment is an investment that pays dividends in daily productivity.',
    'Bilingual typists face unique challenges when switching between languages that use different keyboard layouts or character sets. The mental overhead of switching between input methods can temporarily reduce typing speed. However, regular practice in multiple languages builds cognitive flexibility that benefits other areas of mental performance.',
    'The economics of typing speed are straightforward but often overlooked. If a professional earns fifty dollars per hour and spends six hours per day typing, increasing their speed by twenty-five percent effectively creates an additional ninety minutes of productive time daily. Over a career this translates to significant financial value.',
    'Adaptive typing software uses machine learning to identify individual weakness patterns and generate personalized practice content. These systems track which key combinations cause the most errors or slowdowns for each user, then create targeted exercises that focus specifically on those problem areas for maximum improvement efficiency.',
    'The social dynamics of typing in public spaces have evolved with the proliferation of laptops and mobile devices. The sound of typing in coffee shops and libraries has become ambient background noise. Some establishments have even implemented quiet zones where mechanical keyboard users are asked to use quieter switches.',
    'Typing technology continues to advance with haptic feedback systems that provide physical confirmation of keystrokes without requiring physical key travel. These innovations promise to combine the speed benefits of flat touch surfaces with the tactile satisfaction of traditional keyboards, potentially representing the next evolution in typing technology.',
    'The philosophy of mastery applies elegantly to typing. The journey from unconscious incompetence through conscious incompetence to conscious competence and finally unconscious competence mirrors the path every expert typist has traveled. Understanding this progression helps maintain motivation during the challenging middle stages.',
    'Professional transcriptionists represent the pinnacle of typing speed and accuracy in practical application. Medical legal and general transcriptionists must listen to audio recordings and type what they hear in real time, often dealing with poor audio quality, specialized terminology, and multiple speakers. This demanding application requires both exceptional typing skills and deep domain knowledge.',
    'The connection between typing and thinking is bidirectional. Not only does fast typing allow thoughts to flow more freely onto the screen, but the physical act of typing can also stimulate creative thinking. Many writers report that the rhythmic motion of typing helps them enter a creative state that is different from handwriting or dictation.',
    'Remote work has elevated the importance of typing skills to new heights. When communication happens primarily through text, the ability to type quickly and clearly becomes a differentiating professional skill. Workers who can compose clear concise messages efficiently have a significant advantage in remote collaboration environments.',
    'The measurement of typing performance has become more nuanced over time. Beyond simple words per minute calculations, modern metrics include adjusted words per minute which accounts for errors, consistency scores that measure speed variation, and fatigue indices that track how performance degrades over extended sessions.',
    'Building typing endurance requires the same principles as building physical endurance. Start with comfortable durations and gradually extend practice sessions. Include rest periods to prevent fatigue. Focus on maintaining form even when tired. Over time the duration of peak performance extends and the onset of fatigue is delayed.',
    'The democratization of typing education through free online platforms has made world-class typing instruction available to anyone with internet access. What once required expensive software or in-person classes is now freely available, removing economic barriers to developing this essential professional skill.',
  ],
};
